### ISSUE TITLE
Usage with ionic?

### ISSUE THREAD

**Issue by varmint09** [jakemmarsh/angularjs-gulp-browserify-boilerplate#100]
Hello,

Just wondering what peoples thoughts are for a ionic boilerplate in the same format as this project. I had considered a way of trying to add ionic into this, but I feel two separate codebase makes the most sense, and they can still share the API.

Anyone able to recommend a good ionic boilerplate? I notice there is a mobile friendly version but thats Cordova rather than Ionic.

I generally love how this particular boilerplate is structured, so anything similar would be great.

* I did look myself, but many of them seem to be dead projects...

**Comment by StrikeForceZero** [comment]
I'm the maintainer of the cordova friendly fork. I've heard of ionic but never looked into it.

After giving it a glance and test driving its sample project I can tell you integrating it would probably be no problem. It's built off cordova and I've already made this boilerplate match the cordova project structure.

The only thing I see it doing is in the angular.module(...).run function; it injects `$ionicPlatform` and when `$ionicPlatform.ready(function() { ... }` fires you're in business.

Other than that there's nothing special. I could probably create a repo based off my cordova fork that integrates it. It looks promising and I'd be curious to test it out in place of cordova.

**Comment by varmint09** [comment]
I was unaware of their plans to become a commercial product, what source did that come from?

It might also deter me from using it in that case, but otherwise I would much prefer to be using Angular and Cordova, than Angular -> jQuery -> Cordova; I felt Ionic made the process much cleaner.

But like I said, a commercial aim *might* change things, but it depends how they plan to do that.

**Comment by StrikeForceZero** [comment]
[here was the source I read](http://ionic.io/pricing)

I should rephrase and say it looks like the framework is free but the only benefits using ionic is if you wanted to use all their services/tools.

What do you mean by "Angular -> jQuery -> Cordova"?
my fork uses [ngCordova](http://ngcordova.com/)

Ah.. silly me. [there you go :)](https://github.com/StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate/commit/8df337860c9224dd96961b526bbb13aebdda8a11)

**Comment by StrikeForceZero** [comment]
@varmint09 were you still interested in Ionic support for this boilerplate? Or did you find an alternative boilerplate to use? It would be good to note any closing thoughts for other people searching.

If there is enough interest I could find some time to make another fork implementing Ionic support if someone wanted to follow this boilerplate's practices and design patterns.

Otherwise, @jakemmarsh could probably close this one up, as it's not a *direct issue* to the base boilerplate.

**Comment by varmint09** [comment]
Very interested indeed, I have been experimenting with Ionic and its a great ecosystem.
