### ISSUE TITLE
Protractor fails

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#101]
Default setup when running Protractor test produces this error messages and fails:

    Finished in 4.975 seconds
    [launcher] 0 instance(s) of WebDriver still running
    [launcher] chrome #1 failed 1 test(s)
    [launcher] overall: 1 failed spec(s)
    [launcher] Process exited with error code 1

    npm ERR! node v4.2.1
    npm ERR! npm  v2.14.7
    npm ERR! code ELIFECYCLE
    npm ERR! angularjs-gulp-browserify-boilerplate@1.0.0 protractor: `protractor test/protractor.conf.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the angularjs-gulp-browserify-boilerplate@1.0.0 protractor script 'protractor     test/protractor.conf.js'.

**Comment by alferov** [comment]
It might be an issue with node v4. Try to switch to 0.12 and run it again.
You can use something like [nvm](https://github.com/creationix/nvm) or [n](https://github.com/tj/n) for instant switching between node versions.

**Comment by mnemanja** [comment]
I'll give it a try.

**Comment by jakemmarsh** [comment]
Unable to replicate, so I'm guessing @alferov is right about the node version incompatibility. Closing for now
