### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by billiam13s** [jakemmarsh/angularjs-gulp-browserify-boilerplate#103]
Hi there, 

Are you planning for update to babel 6? Thanks,

**Comment by jakemmarsh** [comment]
Yeah, this will be done eventually. It'll probably be a bit, as the update to Babel 6 was fairly recent and introduced many breaking changes... Plugins, etc. will require updating

**Comment by DrewML** [comment]
Submitted a PR

**Comment by jakemmarsh** [comment]
Done in #133
