### ISSUE TITLE
template.js conflicts and breaks builds

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#110]
Hi, 
Since it's a file which should be ignored, and by default it is ignored, how can a fresh build without it run if it has to exist from the start?

As I understand the file is being automatically generated during the build process, and after each save, but like I've mentioned, if I'm deploying, and doing a clean install, how can the build process work if the `template.js` file is missing?

The file size is 162kb. Could the issue be there? When I try it on the blank project, where the `template.js` size is 1kb, it works. 

It looks like the views.js task takes more time then planned to prepare the `templates.js file`, and when the `browserify` task's turn come the file is not there yet.

Is there a way to make sure that the file will always be generated first, and then other tasks which depend on it?

**Comment by jakemmarsh** [comment]
Ah, hadn't previously tested this on a project with a large number of views but this makes sense. Should be solved in #113, let me know what you think

**Comment by mnemanja** [comment]
I'll test it the first chance I get, but it looks promising.

Good job.

**Comment by jakemmarsh** [comment]
Merged #113
