### ISSUE TITLE
With 'strictDi: true'  Karma does not recognize the @ngInject and throws the error

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#114]
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
  Error: [$injector:strictdi] config is not using explicit annotation and cannot be invoked in strict mode

The 'config' has ngInject.
    /**
     * @ngInject
     */
    var config = function($provide){
    ...

**Comment by DrewML** [comment]
I noticed this today. Seems like it's caused by the fact that [ng-annotate is used as a browserify transform in the gulp bundle](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserify.js#L43), but [not in the karma bundle](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/test/karma.conf.js#L23).

I attempted to fix this locally, but ran into some issues. If you add `browserify-ngannotate` to the list of transforms in `karma.conf.js`, it works, but *only* if you remove the `istanbul` transform for code coverage. It seems like there may be a conflict between tools.

If you do not remove `istanbul` from the transforms list in `karma.conf.js`, you end up getting a strange exception:

```
25 11 2015 17:22:46.047:ERROR [framework.browserify]: TypeError: /Users/andrew/Documents/angularjs-gulp-browserify-boilerplate/app/js/main.js: Cannot read property 'match' of undefined while parsing file: /Users/andrew/Documents/angularjs-gulp-browserify-boilerplate/app/js/main.js
```

The error spit to stdout isn't clear about it's actual origin, so deeper debugging is probably required. I'll probably keep messing around with it.

**Comment by jakemmarsh** [comment]
Hm, hadn't thought of this case. Need to set up continuous integration for this project.

Looks like there's a handful of Karma preprocessors for ng-annotate. None of them with a lot of followers, but worth a try: [1](https://www.npmjs.com/package/karma-ngannotate-preprocessor) [2](https://www.npmjs.com/package/karma-ng-annotate-preprocessor)

**Comment by DrewML** [comment]
Looks like upgrading `Isparta` fixed the issue. PR on it's way

**Comment by mnemanja** [comment]
@DrewML To which version have you updated it to?

**Comment by DrewML** [comment]
@mnemanja Did you also [add `ng-annotate` to the list of browserify transforms in `karma.conf.js`](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/pull/116/files#diff-0be9d25d2ce091e16baef1e0d91d0cf7R25)? That's the other key piece to fixing the issue.

**Comment by mnemanja** [comment]
After updating the packages, and configuring Karma I get this list of errors when running `npm test`:

    karma-coverage@0.2.6 node_modules\karma-coverage
    ├── minimatch@0.3.0 (sigmund@1.0.1, lru-cache@2.7.3)
    └── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.6.0)

> ...@ test ...\webapp
> karma start test/karma.conf.js

    27 11 2015 08:38:23.256:INFO [framework.browserify]: registering rebuild (autoWatch=true)
    27 11 2015 08:38:25.183:ERROR [framework.browserify]: bundle error
    27 11 2015 08:38:25.184:ERROR [framework.browserify]: Error: .../http_interceptor.script.js: Invalid mapping: {"generated":    {"line":null,"column":null,"lastColumn":null},"source":".../http_interceptor.script.js","original":    {"line":1,"column":0},"name":null} while parsing file: ...\http_interceptor.script.js
    [BABEL] Note: The code generator has deoptimised the styling of ".../templates.js" as it exceeds the max of "100KB".
    [BABEL] Note: The code generator has deoptimised the styling of ".../templates.js" as it exceeds the max of "100KB".
    27 11 2015 08:38:26.176:ERROR [framework.browserify]: bundle error
    27 11 2015 08:38:26.176:ERROR [framework.browserify]: Error: .../vendor_libraries/angular_feedback/dist/angular-send-feedback.js: Invalid mapping: {"generated":{"line":null,"column":null,"lastColumn":null},"source":".../vendor_libraries/angular_feedback/dist/angular-send-feedback.js","original":{"line":1,"column":0},"name":null} while parsing file: ...\vendor_libraries\angular_feedback\dist\angular-send-feedback.js

Several files like that, and then these few lines:

    27 11 2015 08:38:34.768:INFO [Chrome 46.0.2490 (Windows 7 0.0.0)]: Connected on socket     xGmQSdbCAocdC-qWAAAC with id 18779500
    Chrome 46.0.2490 (Windows 7 0.0.0) ERROR
      You need to include some adapter that implements __karma__.start method!

For instance the content of the `http_interceptor.script.js` is:

    /**
     * @ngInject
     */
    export default function($httpProvider) {
        $httpProvider.interceptors.push('authHttpResponseInterceptorService');
    };

**Comment by DrewML** [comment]
@mnemanja Are you able to pare down your code to a minimum example that I can reproduce with? Unfortunately it's going to be difficult to troubleshoot your specific project since you have other tooling/config that I can't see.

**Comment by mnemanja** [comment]
I've solved this locally. Basically the errors were being thrown because of 3 things:

1. duplicated directives which were not being used
2. file which were exporting an object literal, but had the comment at the beginning of the file which was the issue
3. last thing being reported was a public library

After ignoring the library, deleting the unused directives with the same name, and removing the comment at the beginning of the file, the errors were gone, and now it's working properly.

The strange thing is the messages that were printed out as a feedback reporting these errors.
Can something be done regarding the karma output, to make it more comprehensible? 

Also, would it possible to change the karma output itself? I like how Jasmine does the reporting of the tasks that were being done: http://i.stack.imgur.com/qscYt.png

And this is Karma's output: http://oi66.tinypic.com/1z3awr7.jpg
Doesn't really tell you which tests have passed.
