### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by jakemmarsh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#115]

**Comment by DrewML** [comment]
Have any preferences on services, or is Travis + SauceLabs okay? (Both free for open-source projects)

**Comment by jakemmarsh** [comment]
That sounds good to me @DrewML! I would've gone with Travis as well, haven't previously worked with SauceLabs

**Comment by DrewML** [comment]
Cool deal. [I've got linting, unit tests, and e2e tests all passing in Travis/SauceLabs with Chrome](https://travis-ci.org/DrewML/angularjs-gulp-browserify-boilerplate/builds/93638868). Need to fix up some stuff for people running locally, but should have a PR in soon.

**Comment by jakemmarsh** [comment]
Done in #132
