### ISSUE TITLE
Production build has a bug on the "clean" task

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#118]
When running a production task automatically on the Jenkins server a pattern occurs.
- First production task run - **clean** task reports that it failed building:
    [14:41:16] Starting 'clean'...
    [14:41:16] Starting 'views'...
    [14:41:16] 'clean' errored after 171 ms
    [14:41:16] Error: ENOTEMPTY: directory not empty, rmdir './build/'
        at Error (native)
- Second production run - **clean** jobs finishes (I guess) and then this error occurs:
[14:46:01] Starting 'clean'...
[14:46:01] Starting 'views'...
[14:46:01] Finished 'clean' after 118 ms
    events.js:141
          throw er; // Unhandled 'error' event
          ^

    Error: EEXIST: file already exists, mkdir '/var/lib/jenkins/jobs/Genolab Frontend (Test     Server)/workspace/genolab-frontend/client.js/src/main/webapp/build'
        at Error (native)

After these 2 runs, one run passes successfully, and then it's back to the square 1, thus the pattern.

**Comment by DrewML** [comment]
Does this happen locally, or just in CI?

**Comment by mnemanja** [comment]
Locally works fine, just the CI.

**Comment by DrewML** [comment]
The issue you're running into is common when another task tries to work in that dir before it's been cleared, but the gulp task dependencies are setup in such a way that this *shouldn't* happen.

First recommendation, without being able to replicate, would be to upgrade the `del` dependency to the latest version (this repo is on 0.1.3, current is 2.1.0).

Note that you'll have to update the clean task slightly, since the API for `del` returns a promise now, rather than accepting a callback.

Untested code, but the task will probably now look something like

```javascript
gulp.task('clean', function(cb) {
  del([config.buildDir]).then(cb);
});

```

**Comment by mnemanja** [comment]
I'll give it a try. Thanks :)

**Comment by DrewML** [comment]
Updated that dep and the `clean` task in PR #120

**Comment by DrewML** [comment]
Ha, you're not alone, apparently (this was replicated with `0.1.3` installed).

![replicated](http://i.imgur.com/JsZO5cI.png)

**Comment by mnemanja** [comment]
I'll try pushing a fresh copy now, but before that the promise - ".then" provides me with an error:

[14:37:31] Starting 'clean'...
[14:37:31] 'clean' errored after 2.81 ms
[14:37:31] TypeError: Cannot read property 'then' of undefined

**Comment by DrewML** [comment]
That could really only mean that the dep didn't get installed correctly, or it wasn't imported correctly. Check #120 for a working example.

**Comment by mnemanja** [comment]
@DrewML I'm running `prod` with these changes locally now. After updating the `clean.js`

    gulp.task('clean', function() {
        return del([config.buildDir]);
    });

and `del` to `2.1.0` the error was fixed. I'll test it on the CI asap. Thanks :)

**Comment by mnemanja** [comment]
The CI still fails. 
I'll test it tomorrow further, and keep you up to date. 

Thanks for the help so far.

**Comment by mnemanja** [comment]
This might be the issue of our CI configuration. I'll close it. Thanks.
