### ISSUE TITLE
Add support for source maps

### ISSUE THREAD

**Issue by jsyrjala** [jakemmarsh/angularjs-gulp-browserify-boilerplate#13]
It seems that currently source maps for javascript files are not generated with `gulp prod`. Would it be easy to add them?

**Comment by jakemmarsh** [comment]
To me, source maps are only useful when developing (and in this boilerplate, development mode doesn't minify). If there's enough feedback, though, this can be added.

**Comment by jsyrjala** [comment]
Users of javascript error logging service like https://errorception.com/ and http://www.muscula.com/ would benefit from source maps in production.

**Comment by jakemmarsh** [comment]
Makes sense. Added in 8d0524877e5e7f8ad260bc96d2c3c75fb44bad02
