### ISSUE TITLE
How to choose order of JS imports?

### ISSUE THREAD

**Issue by Meekohi** [jakemmarsh/angularjs-gulp-browserify-boilerplate#130]
Apologies if this is a n00b question.

[Restangular](https://github.com/mgonto/restangular) depends on [lodash](https://lodash.com/). I tried adding Restangular to a fork of this project, but couldn't figure out how to get lodash to be ahead of Restangular in the final main.js, so keep getting an error.

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module restangular due to:
ReferenceError: _ is not defined
```

or if I try to import it and add it to `requires`:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module lodash due to:
Error: [$injector:nomod] Module 'lodash' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

Of course it works fine if I just use a CDN, include `lodash` before `main.js`, and ignore the bower one. Any tips? Is this a `debowerify` issue? Where would I specify the ordering?

**Comment by jakemmarsh** [comment]
Can you provide an example of how you're importing `lodash` and `restangular`, and how you're injecting them (if at all) into the app?

**Comment by mnemanja** [comment]
I've had the same problem, which I've patched by manually loading it in the
order it requires on the page.

Would be nice to handle it as all other modules.

**Comment by Meekohi** [comment]
@jakemmarsh I added `lodash` and `restangular`, in that order, with `import` statements and to `requires` in `app/js/main.js`. (have tried many variants on this with no luck, but maybe there is some trick I'm missing).

**Comment by Meekohi** [comment]
I just saw this comment in a related thread and wondered if it is relevant here: 
http://stackoverflow.com/questions/14968297/use-underscore-inside-angular-controllers
"its necessary when you add 'use strict' to your file. Since underscore/lodash isn't defined it will throw ReferenceError: _ is not defined... you have to inject it, or use window._"

**Comment by IJsLauw** [comment]
Did anyone manage to resolve this issue in their project other then using CDN? 

I'm trying to do the same slick-carousel needs jquery to be injected before angular, but I can't get it to work using just imports...

**Comment by IJsLauw** [comment]
Ok so this finally did the trick: https://github.com/StrikeForceZero/acgb-boilerplate-shim-example, which I found in this issue: https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/148
