### ISSUE TITLE
Trying add angular-jsonapi to this boilerplate

### ISSUE THREAD

**Issue by pablorsk** [jakemmarsh/angularjs-gulp-browserify-boilerplate#137]
Hi!

I'm trying add [angular-jsonapi](https://github.com/jakubrohleder/angular-jsonapi) to [angularjs-gulp-browserify-boilerplate](https://guides.github.com/features/mastering-markdown/), but gulps says

```
[10:30:27] gulp-notify: [Compile Error]
Cannot find module 'angular-jsonapi' from '/home/angularjs-gulp-browserify-boilerplate/app/js'
```

This is my way. I add to 'packages.json':
```
  "devDependencies": {
    /* ..... */
    "angular-jsonapi": "git+https://github.com/jakubrohleder/angular-jsonapi.git"
}
```

And next, in main.js, this:
import 'angular-jsonapi';
// create and bootstrap application
const requires = [
  /* ..... */
  'angular-jsonapi',
  'angular-jsonapi-rest',
  'angular-jsonapi-local'
];

I'm trying install without bower. Bower work, but return a lot of warnings and not use node_modules. 

Any ideas? Thanks...

**Comment by pascal08** [comment]
You are confusing npm with bower. 

NPM uses package.json. Bower uses bower.json.

**Comment by pascal08** [comment]
Try 'npm install'. It should install the dependency for you since it's already in package.json

**Comment by pablorsk** [comment]
I try this, but is not working. My comment was I don't try use bower, if is possible install this library without bower, better. Or this boilerplate support libraries installed with bower?

Thanks @pascal08. Regards...

**Comment by pascal08** [comment]
Why are you trying to avoid bower? 

Your problem is probably because you're trying to install this the npm way. There is a short installation note in the docs of angular-jsonapi.

**Comment by pascal08** [comment]
bower install angular-jsonapi --save

**Comment by jakemmarsh** [comment]
It's not going to be possible to install this library via npm and import it as you're trying to. You're installing directly from the Github repo, but the project doesn't have an `index.js` or a specified main file. This means it is not technically exporting anything, and so your `import` call will not return anything meaningful.

You're going to have to either use bower as @pascal08 has mentioned, or manually copy its files into your project somewhere.

**Comment by karneaud** [comment]
@pablorsk did this work for you? what exactly did you do?

**Comment by karneaud** [comment]
Tried to `import` the angular module 'angular-jsonapi' and kept getting the following error

>  BABEL] Note: The code generator has deoptimised the styling of "/Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt-lumen-dingo/project/bower_components/parse/parse.min.js" as it exceeds the max of "100KB".

> Uncaught ReferenceError: Parse is not defined
>   at http://localhost:9876/__karma__/var/folders/b2/0p413d516f57gbq62slh0kbr0000gn/T/c2cad44f936ee60025dfcbbb7a3fd3ec.browserify:211 <- bower_components/angular-jsonapi/dist/angular-jsonapi.min.js:1:4003

Is it that we need to exclude this library form the compiling process and include it manually? TRied that as well and ran into anuglar module loading errors.

**Comment by karneaud** [comment]
Tried using maniuplating the browserify config to exclude and include the bower libraries but no go.

```
transform: ["browserify-shim"],
    browser:{
      "parse": "bower_components/parse/parse.min.js",
      "angular-jsonapi":"bower_components/angular-jsonapi/dist/angular-jsonapi.min.js"
    },
    "browserify-shim":
    {
      "parse":
      {
          "exports":"Parse"
      }
    },
    noParse:[
      "./bower_components/angular/angular"
    ],
```
