### ISSUE TITLE
Integrating Ionic instead of AngularJS?

### ISSUE THREAD

**Issue by hassankhan** [jakemmarsh/angularjs-gulp-browserify-boilerplate#144]
Hi, apologies for it not being a real "issue" but I was wondering how I could use Ionic instead of AngularJS? 

I tried installing Ionic using Bower then added `import ionic` wherever `import angular from 'angular'` was, but no luck. Am I missing something obvious? The error it throws is:

```
Uncaught TypeError: _angular2.default.module is not a function
```

**Comment by boadude** [comment]
Same here!

**Comment by StrikeForceZero** [comment]
#100

StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate#1

StrikeForceZero/angularjs-ionic-gulp-browserify-boilerplate

:)

**Comment by hassankhan** [comment]
+1 thanks dude

**Comment by jakemmarsh** [comment]
Good looks @StrikeForceZero, forgot about this fork! Thanks
