### ISSUE TITLE
Question about routes

### ISSUE THREAD

**Issue by udayms** [jakemmarsh/angularjs-gulp-browserify-boilerplate#146]
Where can I find an example with more state routes? The route in the boilerplate is like this:
.state('Home', {
    url: '/',
    controller: 'ExampleCtrl as home',
    templateUrl: 'home.html',
    title: 'Home'
  });

Now, if I change the url to something like:
.state('Home', {
    url: '/home',
    controller: 'ExampleCtrl as home',
    templateUrl: 'home.html',
    title: 'Home'
  })
.state('contact', {
    url: '/contact',
    controller: 'contactCtrl as contact',
    templateUrl: 'contact.html',
    title: 'Contact'
  });

The above code doesnt work. I am probably doing something grossly wrong here. I have spent the last hour or so trying to troubleshoot this. Any ideas?

**Comment by jakemmarsh** [comment]
What is the error you're getting? Have you actually created a module named `contactCtrl` and a template named `contact.html`?

**Comment by udayms** [comment]
I found what was missing. I got it working by adding a name to the state.
