### ISSUE TITLE
How to Retrieve Service Data from Main Controller

### ISSUE THREAD

**Issue by yoavgurevich** [jakemmarsh/angularjs-gulp-browserify-boilerplate#149]
Hi there,

I'm new to Angular so pardon if this code looks awful wrong but I'm simply trying to mimic the introductory logic that allows a controller to retrieve XHR data vis-a-vis a simple GET request and since the way the controller has been set up in this stack looks and behaves very differently from the general examples of bringing in the `$http` as an argument into the controller, I have absolutely no clue at this point how to bridge the two together. This is basically what I'm going for. For reference, I'm trying to get through [this part](https://docs.angularjs.org/tutorial/step_05) of the Angular tutorial. Here's my most coherent attempt at the code:

````javascript
/* controllers/example.js */
function ExampleCtrl($http) {
  // ViewModel
  const vm = this;

  vm.title = 'AngularJS 1.5 Tutorial Using Gulp and Browserify';
  $http
      .get('https://raw.githubusercontent.com/angular/angular-phonecat/master/app/phones/phones.json')
      .success(function(data) {
        vm.phones = data;
      });
}

export default {
  name: 'ExampleCtrl',
  fn: ExampleCtrl
};

````

Thanks in advance.

**Comment by mnemanja** [comment]
I'd say you are missing a controller definition here. You are basically missing this part:

export default **angular.module('ExampleCtrl', ExampleCtrl);**

**Comment by yoavgurevich** [comment]
@mnemanja I believe this is covered by the "bulk-require" logic in `controllers/index.js`, no?

**Comment by jakemmarsh** [comment]
@yoavgurevich you're correct, you shouldn't need the explicit module initialization @mnemanja mentioned due to the bulk-require logic.

I'm not seeing anything obviously wrong in your example code. In what way is this not working? Are you getting a specific error? How are you utilizing `vm.phones` in the view?

**Comment by yoavgurevich** [comment]
@jakemmarsh I'm simply spitting out the data in a table with some search/sort filter queries attached to the element:

```html
<!-- views/home.html -->
<div class="dataView">
        <div class="filter-options">
            <div class="inline-content">
                <strong>Search:&nbsp;</strong>
                <input ng-model="query">
                &nbsp;&nbsp;
                <strong>Sort by:&nbsp;</strong>
                <select ng-model="orderProp">
                    <option value="lastname">Name</option>
                    <option value="position">Position</option>
                </select>
            </div>
        </div>
        <table>
            <tbody>
                <th>Jersey</th>
                <th>Player</th>
                <th>Position</th>
                <tr ng-repeat="player in home.players | filter:query | orderBy:orderProp">
                    <td><p>{{player.jersey}}</p></td>
                    <td><span>{{player.firstname + ' ' + player.lastname}}</span></td>
                    <td><p class="motto">{{player.position}}</p></td>
                </tr>
            </tbody>
        </table>
    </div>
```

**Comment by mnemanja** [comment]
@yoavgurevich you are completely correct. 

I would assume that the connection between your controller and the view is done through the router, where the controller reference is being passed to the view, and thus the "home" object. Do you get anything from the controller in your view? 
I see that you've assigned the title property in your controller as well. Can you access it? 

Like @jakemmarsh asked, what happens exactly when you execute it? Any errors perhaps?

**Comment by yoavgurevich** [comment]
@mnemanja @jakemmarsh So my most updated controller code is at a point where there are NO console errors, and yet there is no output whatsoever on the view:

```javascript
// controllers/example.js
function ExampleCtrl($http) {
  'ngInject';

  // ViewModel
  const vm = this;

  vm.title = 'AngularJS 1.5 Tutorial Using Gulp and Browserify';
  $http
      .get('public/assets/players.json')
      .success(function(data) {
        console.log(data);
        vm.players = data;
      })
      .error(function(error) {
        console.log(error);
      });
}

export default {
  name: 'ExampleCtrl',
  fn: ExampleCtrl
};
```

The updated view:

```html
<!-- home.html -->
<table>
            <tbody>
                <th>Jersey</th>
                <th>Player</th>
                <th>Position</th>
                <tr ng-repeat="player in home.players | filter:query | orderBy:orderProp track by $index">
                    <td><p>{{player.jersey}}</p></td>
                    <td><span>{{player.firstname + ' ' + player.lastname}}</span></td>
                    <td><p class="motto">{{player.position}}</p></td>
                </tr>
            </tbody>
        </table>
```
And just for good measure, here is the JSON file:

```json
[
  {
    "firstname": "Trevor",
    "jersey": "1",
    "lastname": "Ariza",
    "playerid": 2772,
    "position": "F"
  },
  {
    "firstname": "Nick",
    "jersey": "3",
    "lastname": "Johnson",
    "playerid": 203910,
    "position": "G"
  },
  {"firstname": "Josh",
    "jersey": "5",
    "lastname": "Smith",
    "playerid": 2746,
    "position": "F"},
  {"firstname": "Terrence",
    "jersey": "6",
    "lastname": "Jones",
    "playerid": 203093,
    "position": "F"},
  {"firstname": "Joey",
    "jersey": "8",
    "lastname": "Dorsey",
    "playerid": 201595,
    "position": "C-F"},
  {"firstname": "Pablo",
    "jersey": "9",
    "lastname": "Prigioni",
    "playerid": 203143,
    "position": "G"},
  {"firstname": "Dwight",
    "jersey": "12",
    "lastname": "Howard",
    "playerid": 2730,
    "position": "C"},
  {"firstname": "James",
    "jersey": "13",
    "lastname": "Harden",
    "playerid": 201935,
    "position": "G"},
  {"firstname": "Clint",
    "jersey": "15",
    "lastname": "Capela",
    "playerid": 203991,
    "position": "C"},
  {"firstname": "Kostas",
    "jersey": "16",
    "lastname": "Papanikolaou",
    "playerid": 203123,
    "position": "F"},
  {"firstname": "Jason",
    "jersey": "31",
    "lastname": "Terry",
    "playerid": 1891,
    "position": "G"},
  {"firstname": "KJ",
    "jersey": "32",
    "lastname": "McDaniels",
    "playerid": 203909,
    "position": "G-F"},
  {"firstname": "Corey",
    "jersey": "33",
    "lastname": "Brewer",
    "playerid": 201147,
    "position": "G-F"}
]
```

You'll note that I'm trying to spit out the data into the console in the promise callback, yet I must stress again that there is no output whatsoever...

Thanks for sticking with this so far.

**Comment by jakemmarsh** [comment]
I don't think you're using `ui-router` correctly there. It uses `.state`, not `.when`.

Is there a reason you're trying to fetch the players from a URL when they're just hardcoded data points? You could just import them directly in the controller file with `import players from '../../players.json'` and then set them directly on the view with `vm.players = players;`. You don't need any of the `$http` logic.

For the record, this doesn't sound like an issue with the boilerplate. You'd be best served reading the documentation for Angular and ui-router.

**Comment by yoavgurevich** [comment]
@jakemmarsh well in fairness, I was just trying to emulate the logic being presented in [this step of the official AngularJS tutorial](https://docs.angularjs.org/tutorial/step_05). They have a similar JSON file that's locally placed in the repo that they end up using `$http` to fetch data from.

**Comment by jakemmarsh** [comment]
Well that tutorial won't work step-by-step for this boilerplate due to our [custom routing logic](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserSync.js#L16). You might be able to get it to work (although I haven't confirmed) by adding `.json` to the [array of asset extensions](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/config.js#L33). Then, in your `$http.get` call make sure you specify `assets/players.json`.
