### ISSUE TITLE
Add karma-coverage?

### ISSUE THREAD

**Issue by CrankNPlank** [jakemmarsh/angularjs-gulp-browserify-boilerplate#15]
Any chance you'd be willing to add coverage to the seed, ala Istanbul? I've been trying to, and beating my head over it for days, but can't seem to get it right. Either everything will seem to work, but the coverage isn't correct (e.g. 100% 0/0 files) or missing module/dependency errors are thrown.

At any rate, I'd give you a breakdown of what I tried but my efforts were such a jumbled mess that I finally gave-up and couldn't point you to anything specific. Given that test coverage is a pretty common piece of the puzzle, having it as part of the seed would be a welcome addition.

**Comment by jakemmarsh** [comment]
I ran into some of the same issues you mentioned, but eventually got it working! Code coverage added in 9a7ed839a6245d87a2d266d7905f3a0f8a1464ee

**Comment by CrankNPlank** [comment]
Brilliant! Thank you! Looking at it, I didn't have the istanbul transform configured correctly. This is great!
