### ISSUE TITLE
Structure suggestion

### ISSUE THREAD

**Issue by bpalermo** [jakemmarsh/angularjs-gulp-browserify-boilerplate#152]
Hi,

Actually it's not an issue but a suggestion for folder structure.

Sometimes with large projects makes difficult to manage all files in different locations. So what I'm suggesting is something similar to

```
/modules
  /controllers
    exampleCtrl.js   (the example module controller)
    exampleRoute.js   (the example module route)
    example.html   (the example module view)
    example.scss   (the example module stylesheet)
  modules.scss   (should be included in main.scss and should include all modules scss files)
```

What you thing about that?

Thanks,
Bruno

**Comment by jakemmarsh** [comment]
It is relatively common and recommended to organize your files by purpose once your project gets larger. For example:
```
/modules
   /dashboard
      /controllers
         dashboardCtrl.js
     /services
         dashboardService.js
     /views
         dashboard.html
```
(or something similar)

However, my previous thinking in regards to this for a boilerplate is that its rather difficult to enforce a structure like this while still being generic enough to serve as a useful boilerplate to all users. If someone were to come up with a good structure to do this I would be willing to consider it, but as of now I think I'd prefer to keep the project structure as-is. It does still allow for relatively easy modularization once your project grows.

**Comment by bpalermo** [comment]
Does this structure proposed by you would work with the current boilerplate?

Just for completness, I still would keep the services folder and directives

```
/modules
  /controllers
    exampleCtrl.js   (the example module controller)
    exampleRoute.js   (the example module route)
    example.html   (the example module view)
    example.scss   (the example module stylesheet)
  modules.scss   (should be included in main.scss and should include all modules scss files)
/services
  example.js
/directives
  /example
    example.js
    example.html
```

**Comment by StrikeForceZero** [comment]
I'm intrigued by the module directory structure. Makes me feel at home like symfony2 does their "bundles". I do agree the current structure is great for new users to find their way around. Perhaps a module called "example module" containing all the boilerplate examples could suffice. But, I think I would enjoy this only as an option to the default master branch with its current structure. Just my 2 cents.
