### ISSUE TITLE
Adding new Controllers

### ISSUE THREAD

**Issue by bendobos** [jakemmarsh/angularjs-gulp-browserify-boilerplate#153]
Maybe the issue is on my end but I can't add new controllers for some reason. I have the following code:
file js/controllers/demo.js
```
function DemoCtrl($scope) {
	'ngInject';
        console.log('DemoCtrl');
}

export default {
	name: 'DemoCtrl',
	fn: DemoCtrl
};
```

file js/on_config.js
```
function OnConfig($stateProvider, $locationProvider, $urlRouterProvider, localStorageServiceProvider) {
  'ngInject';

  $locationProvider.html5Mode(true);

  $stateProvider
  .state('Home', {
    url: '/',
    controller: 'ExampleCtrl',
    templateUrl: 'home.html',
    title: 'Local Storage Demo'
  })
  .state('Demo', {
    url: '/demo',
    controller: 'DemoCtrl',
    templateUrl: 'demo.html',
    title: 'Demo'
  });

  $urlRouterProvider.otherwise('/');
}

export default OnConfig;
```

When I open the page I get `Error: [ng:areq] Argument 'DemoCtrl' is not a function, got undefined`.
Did I miss something? As far as I can see, the Controller should work like that (I duplicated example.js, basically).

**Comment by mnemanja** [comment]
How are you trying to consume it?

As far as I can see you are missing controller as definition.
Basically `controller: 'DemoCtrl',` should be `controller: 'DemoCtrl as demo',`

and then consume it like so:
```
function DemoCtrl($scope) {
    'ngInject';
  const vm = this;
  vm.title = 'Some string';
        console.log('DemoCtrl');
}

// and then in the view 
{{demo.title}}

**Comment by udayms** [comment]
can i use the ng-controller-"ctrl" in the the markup? I have a page that is not part of my core app and is not accessible by the angular route. How can I add a controller to such a page?

**Comment by marcusmolchany** [comment]
Hey @udayms could you link your:
1. Controller code
2. Template code
3. Config/Location Provider code

It looks like (similar to what @mnemanja was saying) you've left out the `controller as` syntax in the `on_config.js` file. If you look at the Example controller in `on_config.js` it is attached like this:
```javascript
  $stateProvider
  .state('Home', {
    url: '/',
    controller: 'ExampleCtrl as home',
    templateUrl: 'home.html',
    title: 'Home'
  });
```

The [`'ExampleCtrl as home'` syntax](https://docs.angularjs.org/api/ng/directive/ngController) allows you to use `this` instead of `$scope` in your controller code.

To answer your question
> can i use the ng-controller-"ctrl" in the the markup?

Here you will want to refer to your controller with the `controller as` alias in `on_config.js`. If you do `controller: 'DemoCtrl as demo'` like @mnemanja suggested then you would use `demo` through out your template to access anything on that controller and it's scope.

**Comment by otterslide** [comment]
I'm trying to do the same thing.   I'd like to use ng-controller="" as well, and I tried to make a new controller and use ng-controller="NewCtrl as test", but it's not able to find the controller.  How do I attach it to the module? The only example is in on_config with the .state way to do it.  It would be really nice to have additional examples on this boilerplate with multiple nested controllers.

**Comment by jakemmarsh** [comment]
What does the file look like for your `NewCtrl`? The `on_config` isn't actually attaching the controllers to the application, it's just associating them with routes. The controller mounting happens in [main.js](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/main.js#L19) if your controller is defined and exported correctly.

**Comment by otterslide** [comment]
It looks similar to ExampleCtrl.

My controlled does not end up in main.js at all.

index.js is picking it up and adding it to the app.controllers, and main.js has the imports and requires for app.controllers.. I didn't change anything there.

I'm not sure what makes ExampleCtrl end up in main.js while my NewCtrl does not, probably the routing.

I tried to use ExampleCtrl as ng-controller and it seems to be working, so if only I can get my controller to be exported to main.js somehow it should work.

**Comment by jakemmarsh** [comment]
Can you please show us the full file for `NewCtrl`? Also, what does your controller directory structure look like?

**Comment by otterslide** [comment]
I was able to get it working today.  I'm not sure what was going on yesterday, but I just started the app today and the controller is ending up in main.js and it's all working fine.  Maybe some syncing issue.. I'm not sure at all.
Thanks for the help!
