### ISSUE TITLE
Using jQuery plugins

### ISSUE THREAD

**Issue by mcneela86** [jakemmarsh/angularjs-gulp-browserify-boilerplate#154]
I am using `import $ from 'jquery';` to include jquery as shown [here] (https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/90), but I am getting 'angular.js:13236 ReferenceError: $ is not defined'.

I am importing jQuery before Angular, and trying to include [packery](https://github.com/metafizzy/packery) and [angular-packery](https://github.com/lucaslim/angular-packery)

**UPDATE**:
jQuery is actually loading using `import $ from 'jquery';`, I can run `$(document).ready(myFunction);` outside of the AngularJS app. My issue seems to be that I cannot load plugins, I have imported `import 'packery'; import 'ng-packery';` and done the dependency injection, this is when the ReferanceError occurs.

I am guessing that the plugin cannot find jquery or it is being loaded after the plugin looks for it?

**Comment by mcneela86** [comment]
This great little articale solved my problem: http://maximilianschmitt.me/posts/angular-angular-ui-browserify-tutorial/

**Comment by jakemmarsh** [comment]
Glad you got this figured out!
