### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#156]
I've just downloaded the latest version of the boilerplate, set it up, added a button in a view and a method in the controller, and with just clicking it the memory gets consumed and never released. Actually, each 500 kb or so it drops down for around 400kb, but there is roughly 100kb left, so it does not clean it up completely.

I came to this test because I have the same problem, but just on the bigger scale. I've tested this in my application with angular 1.3.15 and 1.5.0, on the clean boilerplate and on a separate angular 1.4.1 application.
The separate angular application does not have this problem. The memory printout jumps up and then gets released with each click, whereas here the memory stays consumed.

`<button ng-click="home.clickingMethod()">Click me</button>`
`vm.clickingMethod = () => {};`

Same thing happens with the clicking event handler in the example directive.

What could be causing this, and how to fix it?

http://postimg.org/image/5h35aphjf/

**Comment by mnemanja** [comment]
I've tested this with pure angular 1.5.0 and the behavior is the same, so it's not the boilerplate problem, if it's even a problem...

**Comment by jakemmarsh** [comment]
Thanks for doing more research into this. Not necessarily good news, but good to hear it's not specific to this boilerplate!
