### ISSUE TITLE
Reload issues

### ISSUE THREAD

**Issue by YouriT** [jakemmarsh/angularjs-gulp-browserify-boilerplate#162]
Hi,

Seems to be really good, I exploring right now. What I figured out is that sometimes reload aren't up to date or that the reload never ends and keeps spinning (and ie: main.js weights half of what it usually does - straightly from the example). Am I the only one to get this issue or is it known and is there a workaround that?

(Using with 1.5.1)

Thanks :)

**Comment by mnemanja** [comment]
Actually the #110 was about the missing 'views' dependency. Build would break because templates.js was being rendered before the view was ready. 

By the way my instalation of the boilerplate works as it should.

**Comment by YouriT** [comment]
I even took the last one you just deployed and the bug remains the same. I just did an `npm i` and then a `gulp dev` working on node `v5.5.0` events seems fine:
```
[09:08:24] Starting 'views'...
[BS] 1 file changed (templates.js)
[09:08:24] Finished 'views' after 23 ms
[09:08:24] Starting 'eslint'...
[09:08:24] Rebundle...
[BS] 1 file changed (main.js)
[09:08:26] Finished 'eslint' after 1.61 s
```

Here is a little video to show that in action: https://youtu.be/EfcC9nZKPnI :)

**Comment by jakemmarsh** [comment]
Thanks for the YouTube video, that's very helpful!

So just to confirm, does this issue only occur for you when changing views? I'm thinking we may want to remove the [browser-sync logic](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/views.js#L22) from the views task, since the Browserify task has to run again when the views change and that task also reloads browser-sync.

**Comment by mnemanja** [comment]
+1 for removing the view from the browserSync. Reason for this is because on my project it feels sluggish waiting for view change to refresh the page, and sometimes it does so twice in the row where the first one is not a full reload.

**Comment by YouriT** [comment]
not sure to fully get what it implies as I just started using gulp and browserSync. I don't really get what it does as even when removing it, the browser is anyhow reloaded. But yeah indeed it seams to only be linked to views and when commenting the logic you spoke about it seems to work smoothly. But as @mnemanja mentioned there is also those twice reloads happening.

**Comment by otterslide** [comment]
I just installed this project and I'm getting the loading very slow/forever problem, as well as double reloads when changing a view.  When changing a .js it's all good.

I'm also wondering, is there any way to collect browser console.error output and bring it back to gulp's console?..

**Comment by otterslide** [comment]
Works good now, thanks.
