### ISSUE TITLE
Karma coverage .js.html dump in /app

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#163]
Hi @jakemmarsh sorry for this late response to this [issue](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/98). Previously I've disabled the coverage, but now here we are again :)

When I download the boilerplate, and run the test this behavior occurs. The /app folder and all of it's children gets populated with .js.html files, and the main html files get altered. I've tried this several months ago, and today, and it behaves the same.

What happens when you do the same? 
For me the Coverage folder does get created, but also the above described situation.

The reason I've added the `coverageReporter` was to configure where the coverage stores the files.

**Comment by jakemmarsh** [comment]
I've still been unable to reproduce this issue, it places the coverage files in `/coverage` correctly for me from a fresh install.

I did just try adding this to the karma config:

```json
coverageReporter: {
    dir: 'test_coverage/'
}
```

and it did place the coverage files in that directory, so it may be worth trying that again.

**Comment by mnemanja** [comment]
So strange... for me it does create and populate the "test_coverage" folder, but also adds and changes all my html files. 
What could be the difference here?

**Comment by jakemmarsh** [comment]
What do you mean it "adds and changes all your html files"? It's going to generate all new coverage files every time it is run, but it shouldn't be modifying any of your app's views

**Comment by mnemanja** [comment]
Unfortunately it does. So we are talking about the clean boilerplate. When
running the unit tests it generates the correct folder, either default
"coverage" or if we configure it to something else, then it generates
.js.html files in /app/js and name them by the js files name. Then if it
finds the .html file at the same level, it rewrites it's content to that of
the generated file.

Very weird, isn't it?

**Comment by mnemanja** [comment]
Since I'm no longer actively working on this project I'll close this issue for now.
