### ISSUE TITLE
Failing tests after upgrade - custom services not detected

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#166]
Good job on #161 but now there is another problem that I'm experiencing.

I'm doing a simple test if the controller exists **[1]**. The controller itself has several Angular services, and several custom services as dependencies. For instance **[2]**.

The test fails (and all other old tests) because of the custom services. When I remove them, and all of the code that uses them in the controller, the test passes.

It starts with the first custom service in the line "showModal" **[3]**

**[1]**
```
var ctrl,
        scope;

    beforeEach(function() {
        // instantiate the app module
        angular.mock.module('app.paymentModule');

        angular.mock.inject(function($controller, $rootScope) {
            scope = $rootScope.$new();
            ctrl = $controller('paymentCtrl', {$scope: scope});
        });
    });

    fit('should exist', function() {
        expect(ctrl).toBeDefined();
    });
```

**[2]**
```
function paymentCtrl($window, $scope, $sce, $timeout, $q, showModal, paymentService, pubSubService, RESTfulService)
```

**[3]**
```
Chrome 48.0.2564 (Windows 7 0.0.0) Unit: paymentCtrl should exist FAILED
	Error: [$injector:unpr] Unknown provider: $modalProvider <- $modal <- showModal
```

**Comment by jakemmarsh** [comment]
Have you added the `ngInject` directive prologue at the beginning of your controller where these dependencies are imported/used? See the [example service](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/services/example.js#L2)

**Comment by mnemanja** [comment]
Yup, I have it everywhere where I have dependencies. Also I'm using the
strictDI option to be certain I don't miss any.

**Comment by mnemanja** [comment]
By the way, this is the way I'm consuming it in the project:

**show_modal.service.js**
```
"use strict";

import angular from 'angular';
let app = angular.module('app.showModal', []);

/**
 * Show Modal window
 * @returns {Function}
 *
 * @ngInject
 */
function showModal($modal) {
    return function (scope, id, template, callback, hideCallback) {
        ...
    };
}

export default app.service('showModal', showModal);

```

**_index.js** which of the Payment controller which consumes it.
```
'use strict';

import angular from 'angular';
var bulk = require('bulk-require');

import showModal from '../shared/misc/services/show_modal.service';

export default angular.module('app.paymentModule', [showModal.name]);

bulk(__dirname, ['./**/!(*_index|*.spec).js']);
```

And then the **payment.controller.js** just consumes it:

```
"use strict";

import paymentModule from '../_index';

/**
 * paymentCtrl
 *
 * @ngInject
 */
function paymentCtrl($window, $scope, $sce, $timeout, $q, showModal, paymentService, pubSubService, RESTfulService) {
    ...
}

export default paymentModule.controller('paymentCtrl', paymentCtrl);

```

And at the end it complaints for every custom service. Others are defined on an upper level as a dependency.

**Comment by mnemanja** [comment]
Actually forget about it. This was the problem:

**angular.mock.module('app.paymentModule');**

works when defining it like this:
**angular.mock.module('app');**
```

    beforeEach(function() {
        // instantiate the app module
        angular.mock.module('app.paymentModule');

        angular.mock.inject(function($controller, $rootScope) {
            scope = $rootScope.$new();
            ctrl = $controller('paymentCtrl', {$scope: scope});
        });
    });
```
