### ISSUE TITLE
Get compile error by browserify 

### ISSUE THREAD

**Issue by Pooriafd** [jakemmarsh/angularjs-gulp-browserify-boilerplate#185]
When view is too heavy and time taking to build 
browserify runs in parallel and gets compile error since app/template/template.js is not available yet

**Comment by mnemanja** [comment]
Hi @Pooriafd,
Might be related to this https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/110

The solution was to have a *views* task be a dependency.

**Comment by Pooriafd** [comment]
Hi @mnemanja Thank you for quick response,
yes that seems to be the right answer :)
i suggested a code change to have it in master branch

**Comment by jakemmarsh** [comment]
Should be fixed in #186
