### ISSUE TITLE
Don't use bower anymore?

### ISSUE THREAD

**Issue by Meekohi** [jakemmarsh/angularjs-gulp-browserify-boilerplate#188]
So I noticed that bower has been mostly removed from here (although debowerify is still on by default?), and seems to have generally fallen out of favor. Is "best practice" now to only use `npm`? What is the best way be to handle any packages that are not available via `npm` and we used to use from bower?

**Comment by jakemmarsh** [comment]
Bower was never used as a part of this boilerplate. The debowerify feature was added as a request by users who choose (or are forced) to use Bower components. I would always recommend using npm over Bower if the package is available there.

If the package is only available via Bower, then you still have the option of installing that way. You then need to include it somewhere in the JS or SASS pipeline to include it in the build process

**Comment by Meekohi** [comment]
Thanks!
