### ISSUE TITLE
module.exports = undefined is not a function

### ISSUE THREAD

**Issue by georgelviv** [jakemmarsh/angularjs-gulp-browserify-boilerplate#19]
Hello! For first thank you for great boilerplate.
When getting up, have error `Uncaught TypeError: undefined is not a function` on
`app/js/controllers/_index.js:5`
String:
`module.exports = angular.module('app.controllers', []); `
In this case angular is undefined.
P.S. *Windows 8*
P.S. P.S I try this getting up to make on other computer (*windows 7*) and all works great! And i found one thing. If rewrite `angular` to `windows.angular` (on *windows 8*) that works great. Can help me?

**Comment by jakemmarsh** [comment]
(Disclaimer: I'm on Mac OSX).

I just did a fresh clone, `npm install`, and `gulp dev` and everything seemed to function correctly. I was not able to replicate this issue. Have you made sure to run `npm install` before compiling or running the application? Also, just as a side note: `window.angular` may resolve the issue but I would not recommend it. That's attaching angular to the window, making it globally accessible.

If you're still having this issue after a fresh clone, install, and compile, I'll try to find a Windows machine to replicate your environment on. Keep me updated @georgelviv!

**Comment by georgelviv** [comment]
Hi! thanks for response! I think, perhaps it problem with node version compability, i have node  v0.12.0, when npm installing, i have error with node version compability (in boilerplate seems it requirements v0.10.0 )

**Comment by jakemmarsh** [comment]
@georgelviv I've updated the node dependency to 12.0 (and pushed this change) and still noticing no problems

**Comment by jakemmarsh** [comment]
Closing this since I haven't heard any updates from you!
