### ISSUE TITLE
StateProvider not working on prod

### ISSUE THREAD

**Issue by GazousGit** [jakemmarsh/angularjs-gulp-browserify-boilerplate#190]
Hi, I'm not able to reach some of my url on prod.
For example, my app redirect to ******/public if user is not logged, but if I apply ****/public again on my web browser I'll just get a 404.
Do I have to config apache/nginx to redirect each url on it's state from the stateProvider.
Or I missed something ?

OnConfig:
`
    $stateProvider
        .state('Home', {
            url: '/',
            controller: 'ExampleCtrl as home',
            templateUrl: 'home.html',
            title: 'Home',
            data: {requiresLogin: true}
        });

    $stateProvider
        .state('Login', {
            url: '/login',
            controller: 'LoginCtrl as login',
            templateUrl: 'login.html',
            title: 'Login'
        });

    $stateProvider
        .state('Register', {
            url: '/register',
            controller: 'RegisterCtrl as register',
            templateUrl: 'register.html',
            title: 'Register'
        });

    $stateProvider
        .state('Public', {
            url: '/public',
            controller: 'PublicCtrl as public',
            templateUrl: 'public.html',
            title: 'Public'
        });

    $urlRouterProvider.otherwise('/public');
`

**Comment by mnemanja** [comment]
@GazousGit you are correct. 
Your server needs to be configured to let the angular router do it's job. 

It has only to do with routes handling and  nothing else in your case. 

Set your server to always send users to the root of your application, and the angular router (ui-router) will do the rest. 

Best of luck.

**Comment by GazousGit** [comment]
Thanks, indeed after doing some work on the web server I managed to re-route ulr to the stateProvider of angular.

**Comment by mnemanja** [comment]
@GazousGit You are welcome.

**Comment by danielllano** [comment]
@GazousGit did you use some apache module? Or how did you managed to re-route ulr to the stateProvider of angular? I'm having the same issue. Thanks.
