### ISSUE TITLE
Disable debug data

### ISSUE THREAD

**Issue by marcusmolchany** [jakemmarsh/angularjs-gulp-browserify-boilerplate#194]
Disabling debug data is a [production performance recommendation](https://docs.angularjs.org/guide/production). It can be turned off by adding this line to the module config:

```js
myApp.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);
```

The only issue arises during protractor tests when debug info _should_ be enabled. This can be done by running the following line in the browser.

```js
angular.reloadWithDebugInfo();
```

On the [following issue on the angular/protractor repository](https://github.com/angular/protractor/issues/2116) @akshaybapat recommends adding the following to protractor tests:

```js
browser.executeScript('angular.reloadWithDebugInfo()');
```

Not 100% sure the best way to do this. In other projects I've set an environment variable or a variable on `window` to toggle this option on or off.

**Comment by marcusmolchany** [comment]
The file that would change in this project would be [on_config.js](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/on_config.js)

**Comment by diego-vieira** [comment]
Just came across this and was wondering why it wasn't in the boilerplate, thanks

**Comment by jakemmarsh** [comment]
Good call. Done in #198
