### ISSUE TITLE
How to add a new module?

### ISSUE THREAD

**Issue by vestor** [jakemmarsh/angularjs-gulp-browserify-boilerplate#197]
Hi, I am a bit new to browserify and gulp. If I wanted to add an external module, for example: socket.io how would I go about doing it in the correct way?

**Comment by jakemmarsh** [comment]
You should be able to do this via npm and Browserify:

`npm install --save-dev socket.io`

```js
import io from 'socket.io';

// can now use socketio
```

https://www.npmjs.com/package/socket.io

**Comment by vestor** [comment]
Thanks!
