### ISSUE TITLE
Bower...

### ISSUE THREAD

**Issue by varmint09** [jakemmarsh/angularjs-gulp-browserify-boilerplate#20]
What about support for modules installed using Bower? How do you suggest that might work?

**Comment by jakemmarsh** [comment]
I've just pushed f05d2fc5dc30759c09d946e3b4467971e64aa872, which should allow you to `require()` bower components just as you would npm modules.

**Comment by varmint09** [comment]
Hi,

I have noticed that it seems to throw an error if I include angular through npm, and then if a bower component installs angular as a dependency, I think it doesn't know which to choose, or maybe includes it twice?

**Comment by jakemmarsh** [comment]
It makes sense that that would result in some sort of issue. I'm not a personal user of Bower and I haven't found any solutions from some initial googling, but I'll continue looking for possible resolutions to the issue.
