### ISSUE TITLE
Can't start the application

### ISSUE THREAD

**Issue by privatebasim** [jakemmarsh/angularjs-gulp-browserify-boilerplate#200]
Hey guys,

I cloned the repo locally and run `npm install` and when I run `npm run dev` it gave me error like this "'NODE_ENV' is not recognized as an internal or external command, operable program or batch file." so I edit this line in packages.json to add SET keyword as so ("dev": "NODE_ENV=development ./node_modules/.bin/gulp dev").

It fixed the problem but still can't start the server, seems that the gulp script is not run. Any clue? Thanks.

**Comment by jakemmarsh** [comment]
I'm unable to replicate this from a fresh clone/install. I'm also not sure what you mean by "add SET keyword", as the snippet you pasted is identical to the "dev" command in master.

Is it throwing any specific error(s)? What version of node and npm are you on?

**Comment by privatebasim** [comment]
Sorry. My bad.
Node version is **v4.4.3** and npm version is **2.15.1**

This line **before** editing: ("dev": "NODE_ENV=development ./node_modules/.bin/gulp dev").
This line **after** editing: ("dev": "SET NODE_ENV=development ./node_modules/.bin/gulp dev").

And the following **TWO** screenshots for **before** and **after** I edit this line:
![withoutset](https://cloud.githubusercontent.com/assets/10829464/15987175/b26bde44-301f-11e6-8ac8-4337e62cd28e.png)

![withset](https://cloud.githubusercontent.com/assets/10829464/15987176/b29f86a4-301f-11e6-8aa4-5bfce011563b.png)

Thanks.

**Comment by jakemmarsh** [comment]
Oops, I was not aware that environment variables could not be set the same way across both OSX and Windows. Sorry about this.

I'll put out a fix when I get the chance, but until then your fix should just be joining the two commands by a double ampersand:
```
SET NODE_ENV=development && ./node_modules/.bin/gulp dev
```

**Comment by japostigo-atsistemas** [comment]
For Windows I had to invert the slashes, so the working command is:
```
  "scripts": {
    "dev": "SET NODE_ENV=development && .\\node_modules\\.bin\\gulp dev",
    ...
```

**Comment by privatebasim** [comment]
Thanks guys, it works good.
