### ISSUE TITLE
Quesion

### ISSUE THREAD

**Issue by trsh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#205]
Whats the best practice to add my custom JS library, for using in angular directives?

**Comment by jakemmarsh** [comment]
You should use Javascript modules by exporting and importing your library:

**my_lib.js**:
```js
const myLib = {
  doSomething() {
    return 4;
  }
};

export default myLib;
```

**my_directive.js**:
```js
import myLib from './my_lib';

// do something with myLib, make your directive, etc.
```
