### ISSUE TITLE
Any known issues with uglify in gulp prod?

### ISSUE THREAD

**Issue by varmint09** [jakemmarsh/angularjs-gulp-browserify-boilerplate#32]
Hello,

If I  leave the following code in my browserify() file, then although gulp prod is successful, none of the routes work.

This app works in dev builds, just went i run the gulp prod, nothing happens, but I get no errors either?!

      .pipe(gulpif(global.isProd, streamify(uglify({
        compress: { drop_console: true }
      }))))

Is this a known issue with this boilerplate, and what solutions, or tips for debugging this error are there? I have nginject etc used everywhere. I do make use of bower packages base64-upload and angular-scroll-glue and none packages, and the baseSixtyFourInput directive.

I am at a lose end it appears!

Any help welcome!

**Comment by jakemmarsh** [comment]
What do you mean by "nothing happens" when you run gulp prod? Are new files generated in the `/build` directory? Does the terminal show the gulp tasks being run?

I just did a fresh clone and npm install, and `gulp prod` worked. I then used Bower to install the libraries you mentioned (angular-base64-upload and angular-scroll-glue), and included them as so:

```javascript
var x = require('angular-base64-upload');
var y = require('angular-scroll-glue');
```

and ran `gulp prod` again, and still no errors and seems to be working correctly.

**Comment by varmint09** [comment]
Hello,

Sorry, I mean the client-side breaks so nothing happens (As in I cannot navigate etc), as I get an injection error in the compiled main.js.

It does create the build file, its just it only works if I comment out the uglify step.

I might try taking a new release of the boilerplate, and my code into it again.

**Comment by jakemmarsh** [comment]
What is the actual error and stack trace in the compiled `main.js`? All the uglify step does is minify the code and remove `console.log` lines, so it may be an error in your actual code that only presents itself when minified.

**Comment by jakemmarsh** [comment]
Any update on this @varmint09?

**Comment by varmint09** [comment]
Hi,

I have moved all my development work into the latest version, and it brought about several issues, and I am unsure if they are due to recent changes to the framework, or if they are a bug.

In my app/index.html I include certain components that are used on all pages, like so;

<div ng-include src="'layouts/header.html'"></div>

I get a infinitely loading page if I leave these in...

How would I do this with the new partialify() addition? I would probably suggest this gets added to the documentation as its a common use case.

I am not totally convinced all the recent improvements have really made the framework any easier to use, or at least if they have, the instructions for the boilerplate should be updated too, as part of their PR.

* It might well be that how I have came to use the boilerplate has meant I can no longer use yours, but I would have expected me to be able to migrate from the old to the new much easier. Or am I one of the few that are using it for quite a large project, and thats why I get these issues?

**Comment by DrewML** [comment]
@varmint09 I've used the boilerplate recently on a new *large* project without issues. However, I personally don't think it's super common for people to go back and pull in updates from a boilerplate into existing projects. Of course, that's purely my opinion.

In regards to your comments about documentation, it would be awesome if you could open issues for explicit items you felt were missing in the documentation. This would not only help you, but help anyone else in the future searching for similar issues.

As far as the `partialify` updates, the example provided within `routes.js` should be pretty straight-forward -- just your standard require call. Can you provide more information about specifically what doesn't make sense?

In regards to the main issue you're reporting, I really don't think we have enough information from you to help you out. If you can send a minimal example of the issues, I'm sure we can help. Unfortunately, it's *really* hard to diagnose what issues you are experiencing with the limited info we've been given.

You mentioned you get an injection error when you run a production build -- can you provide an example of that exception?

**Comment by jakemmarsh** [comment]
In addition to what @DrewML mentioned, I just have one question. You say you're "including certain components" in your `index.html`. Could you provide some sample code of this? No new files should be explicitly loaded in `index.html`, because the Gulp tasks will automatically concatenate all your Javascript and CSS into the two files already being loaded.

**Comment by varmint09** [comment]
Hello,

I certainly might no offence if my post caused any, and I do appreciate my use case is not typical, anyway, here goes!

* The reason I wanted to merge my work back into the latest boilerplate is two-fold, one is because my gulp prod builds do not work, and secondly because of some of the new features added are useful to me; specifically the gzip task, and the improved way of loading files with the bulk-require.

The example of the partial templates is clear in the routes file, but the problem I have is better shown in code;

<!doctype html>
<html class="no-js">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title ng-bind="pageTitle"></title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
      <link rel="stylesheet" href="css/main.css">
  </head>
  <body>
    <div ng-include src="'layouts/header.html'"></div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-1">test1</div>
        <div class="col-xs-12 col-md-10">
          <div ui-view></div>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
      <div ng-include src="'layouts/footer.html'"></div>
    <script src="js/main.js"></script>
  </body>
</html>

It does not seem to like the ng-include parts, the page will only stop loading when I comment those lines out, so I would imagine its partialify that is probably related to this? This works in the boilerplate from a few months back before partialify and gzip was added.

---
The issues with injection only occur on the boilerplate version, but I guess my choice is; make my code work in the latest boilerplate, or fix the injection issue in the old one.
---

I would be happy to improve documentation of things as my contribution, once I get my own issues resolved, as I do appreciate the effort behind this boilerplate!

**Comment by varmint09** [comment]
Hi @DrewML @jakemmarsh any feedback? :)

**Comment by DrewML** [comment]
Hey @varmint09,

Sorry for the delay. You hit the nail on your head in your last comment.

When I submitted the PR to use `partialify`, my goal was to avoid the current pattern of having a non-browserify compiled file sitting on disk. However, when I decided to use `partialify`, I totally didn't consider the use-case of including templates from a non-JS file (in this case, the `ng-include` directive).

Having said that, I'll have to submit a PR for a different solution. I was looking at `browserify-ng-html2js` as a possibility, and I think that may work out.

@jakemmarsh, you may want to revert that merge for the time being.

**Comment by jakemmarsh** [comment]
@DrewML @varmint09 reverted in 3f693fc9306f08464844fdf96ff3352180fcc1cc. Good catch on that, I hadn't thought of that use case either

**Comment by varmint09** [comment]
Many thanks, I looked at the same library as mark but that was at 2am this morning. One for one of us to add in future I guess, but my primary concern was my breaking App and as I'm still new to the angular side I tend to look and think I'm at fault first!

**Comment by varmint09** [comment]
Hello,

I have investigated further, and although my production gulp task works again, it only works when I set mangle to false, which isn't what I need!

My next hunch is that if I uglify the main.js it no longer works nicely with lodash, and I do rely on that library, so how would I add lodash to this boilerplate? I currently load it in via the <head>

      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.4.0/lodash.min.js"></script>

I tried the bower nglodash package, but it includes angular, and then that breaks the file, as the angular folder is in node_modules and bower_components.

I did try;

var _ = require('lodash'); 

angular.element(document).ready(function() {

  var requires = [
   ...
    'app.controllers',
    'app.services',
    'app.directives',
   ...
   '_'
  ];

But that doesnt seem to work either and throws an error in the console too. I also include the primus library, but thats client side generated so I would not ever be able to uglify that as part of the build.

Am I on the right track with whats breaking my uglification, and equally, an example of how to use 'lodash' with this boilerplate would be awesome!

* I do have some tasks to merge in soon, including one to automate the changing of variables in index.html.

Many thanks!

**Comment by jakemmarsh** [comment]
I'm not sure why you're including lodash that way. You can install lodash as a dependency via npm, and then just do `var _ = require('lodash')`. I do this in all of my projects. This will then be required and concatenated correctly at the Browserify step.

**Comment by varmint09** [comment]
So I don't need to add it to the requires[] ?

**Comment by jakemmarsh** [comment]
No. That list of requires is specifically Angular modules (controllers, services, setc), and does not need to be modified in this boilerplate unless you're changing the structure and/or adding new Angular modules specifically.

**Comment by varmint09** [comment]
Sorted, thanks!

I'll see how that helps uglify now.

**Comment by varmint09** [comment]
Hi,

The issue still occurs, and I get no error messages if I uglify the build with mangle set to true, I do not have html5mode set to true, but I tried logging around the state change event and nothing occurs, the event doesnt seem to be fired.

A sample from route.

  $stateProvider
    .state('home', {
      url: '/',
      controller: 'HomeCtrl',
      controllerAs: 'home',
      templateUrl: 'home.html',
      title: 'Home'
    })

This all works when mangle is false, but not when true, and our browserify tasks are the same.

* I will send a PR for some useful gulp tasks on Monday, its 2am now!

**Comment by varmint09** [comment]
I found it, and its maybe worth a mention for someone equally newbish.

```
    .state('login', {
      url: '/login',
      controller: 'LoginCtrl',
      templateUrl: 'login.html',
      title: 'Login',
      resolve: {
      // add the dependencies to the routes you resolve too!
        authenticated: ['$dependencyOne', '$dependencyTwo', function ($dependencyOne, $dependencyTwo) {
         // something with $dependencyOne, $dependencyTwo
        }]
      }
    })
```

**Comment by jakemmarsh** [comment]
I'm going to close this issue, as I think it's issues specific to your project at this point!
