### ISSUE TITLE
Question: Best way to include Material Design

### ISSUE THREAD

**Issue by FunkeDope** [jakemmarsh/angularjs-gulp-browserify-boilerplate#37]
What's the best way to include Material Design with this stack? Should i just add it using bower/npm from https://github.com/angular/material or would I wanna use the SASS version?

I'm just not 100% sure the best way too add this on.

**Comment by jakemmarsh** [comment]
In my opinion, including external CSS libraries can always get a little messy. You either end up copying & pasting it into your own styles (thus not receiving future updates), or have to refer to the file via it's `node_modules/` or `bower_components/` path. In this case, I would probably recommend just using their [CDN approach](https://github.com/angular/material#cdn) to load the CSS directly inside `index.html`. This will also cause the added benefit of their CDN caching and delivery.
