### ISSUE TITLE
Watchify not calling rebundle after templates change

### ISSUE THREAD

**Issue by rosterloh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#38]
I'm not sure if this is an issue for everyone but if I change a template I get templates.js being recreated but browserify rebundle doesn't run. Anyone else have this?

**Comment by jakemmarsh** [comment]
This should be working, and I cannot replicate the issue. Could you give us any more detail on the issue/your project setup?

**Comment by rosterloh** [comment]
I'm not really sure what the issue was but it's fixed now. Thanks.
