### ISSUE TITLE
Requiring local libraries

### ISSUE THREAD

**Issue by hoodsy** [jakemmarsh/angularjs-gulp-browserify-boilerplate#56]
For some reason I seem to be unable to require local scripts like:

<script src="../wow.min.js"></script>

I can require any npm dependencies without a problem.

**Comment by jakemmarsh** [comment]
Sorry, looks like your example is missing @hoodsy?

**Comment by hoodsy** [comment]
Oops. but it's no worries. I guess I was just wondering if I could have local libraries that aren't offered by npm/bower included in index.html. I'm currently just placing a minified js file in /build to accomplish this.

**Comment by jakemmarsh** [comment]
The (usually better) way to achieve this would be to just include the local JS files somewhere within the tree of `/app/main.js`, so that it's included and bundled in the Browserify process.

**Comment by aleixpellicer** [comment]
@jakemmarsh they're not included in my Browserify process, any other way?

**Comment by aleixpellicer** [comment]
@jakemmarsh I solved it by modifying the config.js of gulp:

      'browserify': {
         'entries'   : ['./app/js/sweet-alert.js','./app/js/main.js'],
         'bundleName': 'main.js',
         'sourcemap' : true
      },

Hope it helps people who are not too familiar with gulp.

**Comment by hoodsy** [comment]
@aleixpellicer thanks for the pointer aleix! I'm actually encountering this issue again. I tried your solution, to no avail. 

If I require the dependencies in index.js, similar to my angular modules, I error out. This is all connected to the issue of bower installing another version of angular, per #46.

Do you reference your sweet-alert dependency anywhere else @aleixpellicer?

**Comment by aleixpellicer** [comment]
@hoodsy you are welcome :)

I have it like this:

    // angular modules
    require("angular-ui-router");
    require("angular-sweetalert");
    require("./templates");
    require("./controllers/_index");
    require("./services/_index");
    require("./directives/_index");

    // create and bootstrap application
    angular.element(document).ready(function () {
      var requires = ["ui.router", "templates", "app.controllers", "app.services", "app.directives", require("angular-animate"), require("angular-cookies"), "oitozero.ngSweetAlert"];
      // mount on window for testing
      window.app = angular.module("app", requires);
      angular.module("app").constant("AppSettings", require("./constants"));
      angular.module("app").config(require("./routes"));
      angular.module("app").run(require("./on_run"));
      angular.bootstrap(document, ["app"]);
    });

Now, I'm not sure if the `require("angular-sweetalert");` on the top does anything at all, I might just have just forgotten to delete that line after trying stuff. I think what worked was to include on browserify the oitozero.ngSweetAlert version for AngularJS (like I posted on my last comment here), then I just referenced it on the require array `"oitozero.ngSweetAlert"`. Hope it helps you and anyone else facing this issue.

**Comment by justin-umesh** [comment]
'browserify': {
     'entries'   : ['./app/js/sweet-alert.js','./app/js/main.js'],
     'bundleName': 'main.js',
     'sourcemap' : true
  },

not working for me
