### ISSUE TITLE
Gulp prod

### ISSUE THREAD

**Issue by boadude** [jakemmarsh/angularjs-gulp-browserify-boilerplate#58]
Why when i execute <code>gulp prod</code> and the see the <code>main.js</code> file in <code>/build</code> i see code whit absolute routes?

Like
<code>
"C:\\..\\User\\Documents\\xxx\\xxx\\node_modules\\angular\\index.js"
</code>

**Comment by aleixpellicer** [comment]
+1 I also see them, I have no clue why they are for

**Comment by jakemmarsh** [comment]
This is not a problem, this is just a result of the Browserify step. It's how Browserify identifies and refers to all the different local files you've `require`'d throughout your project.

You could use something like [remapify](https://github.com/joeybaker/remapify) to clean these paths up a little bit, but I don't know of any way to eliminate them entirely.

**Comment by boadude** [comment]
Already found the solution to this. Go to <code>gulp/tasks/browserify.js</code> and edit the line 28.

<code>fullPaths:true</code> 
for
<code>fullPaths:false</code>

**Comment by jakemmarsh** [comment]
Ahh, even easier! Good catch :+1:
