### ISSUE TITLE
protractor task should depend on prod task

### ISSUE THREAD

**Issue by bvarga** [jakemmarsh/angularjs-gulp-browserify-boilerplate#61]
Hi,

simply cloning the repo than running `gulp protractor` will fail, since the files are not bundled, so in my opinion the `protractor` task should depend on the task `prod`

**Comment by jakemmarsh** [comment]
The downside to making the `protractor` task depend on `prod` is that it will then run `prod` EVERY time you want to run the tests, adding extra processing and wait time on each run (even if your app is already bundled). 

From a high-level point of view, I wouldn't expect anyone to be immediately running tests without first writing any code or running either `gulp dev` or `gulp prod`, but I do understand your point. I'll think about this

**Comment by jakemmarsh** [comment]
Closing. I don't think making `protractor` dependent upon `prod` would be the best solution for this.
