### ISSUE TITLE
Never ending protractor task

### ISSUE THREAD

**Issue by bvarga** [jakemmarsh/angularjs-gulp-browserify-boilerplate#62]
Running the `protractor` task by typing `gulp protractor` will never ends.

**Comment by bvarga** [comment]
googling a little bit find that the [gulp-exit](https://www.npmjs.com/package/gulp-exit) package may help, but I'm not sure this is the right solution. 

hovever modifying [protractor.js](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/protractor.js) like this will do the job:

```js
var exit = require('gulp-exit');

gulp.task('protractor', ['e2ebuild'], function() {
  return gulp.src('test/e2e/**/*.js')
    .pipe(protractor({
        configFile: config.test.protractor
    }))
    .pipe(exit())
    .on('error', function(err) {
      // Make sure failed tests cause gulp to exit non-zero
      throw err;
    });
});
```

**Comment by jakemmarsh** [comment]
Good catch! I believe I've fixed the issue without adding another dependency in ee7f3e5f0ac421b5295c94801fa1079071f44bc3
