### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by loistaler** [jakemmarsh/angularjs-gulp-browserify-boilerplate#63]
Hello

when i try to setup the project and run `npm install`, i get the following error:

```
npm ERR! git clone --template=C:\Users\Lukas\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/douglasduteil/nomnom.git C:\Users\Lukas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-douglasduteil-nomnom-git-62bc39f3: Cloning into bare repository 'C:\Users\Lukas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-douglasduteil-nomnom-git-62bc39f3'...
npm ERR! git clone --template=C:\Users\Lukas\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/douglasduteil/nomnom.git C:\Users\Lukas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-douglasduteil-nomnom-git-62bc39f3: fatal: unable to access 'https://github.com/douglasduteil/nomnom.git/': Failed to connect to github.com port 443: Timed out
```

**Comment by jakemmarsh** [comment]
Just did a fresh clone and npm install, was not able to reproduce this problem. It looks like it's timing out when attempting to clone [douglasduteil/nomnom](https://github.com/douglasduteil/nomnom), but everything looks okay with that repo.

Have you added any of your own dependencies? Did you make any other changes before/after running `npm install`?

**Comment by loistaler** [comment]
thanks for your reply, i tried it again today and suddenly it worked :+1:  (i got an error that python 3 isn't supported by some dependency, but gulp dev still worked, so no problem there for now :grin: )

**Comment by Mioby** [comment]
**Hello
I have the same issue but doesn't seem to work by magic like @loistaler.
And I've got that too :** 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
[npm-debug.txt](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/files/264601/npm-debug.txt)
