### ISSUE TITLE
Too many missing dependencies...

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#64]
I remember when I first found this project, I liked it very very much because it worked out of the box, and I'm using it still.

I've tried to get a latest one and there are too many missing dependencies. I've tried adding them all, but at the end I've ended up with missing isObject during the gulp dev.

Please fix all the dependencies, and make it work like before.

I've tried the older one `17a7454aaee3824707e5113f3f9290699c85b73b` and that one works. Shame for the current one :(

**Comment by jakemmarsh** [comment]
Sorry, can you walk me through the process you're doing to get the latest version and install dependencies? I just did a fresh `git clone`, `npm install`, and `gulp dev` and it all worked just fine. Doesn't seem to be missing any dependencies, unless you're taking a different approach.

**Comment by jakemmarsh** [comment]
Closing, as I wasn't able to reproduce and haven't heard an update.
