### ISSUE TITLE
browserSync.active doesn't working

### ISSUE THREAD

**Issue by danywheeler** [jakemmarsh/angularjs-gulp-browserify-boilerplate#65]
all tasks with browserSync.active won't work, is it a browser-sync version problem ?

**Comment by jakemmarsh** [comment]
Good catch, looks like `browserSync.active` may have been removed. The conditional reloading doesn't appear to be necessary though! Fixed in ba347fbc291b3612a987aef20daacd1dd1119c36

**Comment by danywheeler** [comment]
I think if it's not html changed we cloud use browserSysc.stream() to make browser sync @jakemmarsh what do you think ?

**Comment by jakemmarsh** [comment]
@danywheeler we were actually already just streaming the updates once through use of the `stream: true` option, but it looks like browser-sync has replaced that with the `browserSync.stream()` that you've mentioned. Swapped all instances out in ee6ba3b8790921552a6fa1ff45122d14878e8c99
