### ISSUE TITLE
Bootstrap-sass requires latest gulp-sass

### ISSUE THREAD

**Issue by magnuslundstedt** [jakemmarsh/angularjs-gulp-browserify-boilerplate#68]
Hi, 

I'm using this awesome boilerplate a lot, together with bootstrap-sass. For this to work great I always have to upgrade gulp-sass. I't would be nice if this boilerplate just included the latest version by default. This way the glyphicons will work. 

See the following thread; 
https://github.com/twbs/bootstrap-sass/issues/927

As for those who're looking for instructions on setting up bootstrap-sass with this boilerplate, simply do this; 

1) Install bootstrap-sass; npm install bootstrap-sass --save-dev
2) In file “gulp/tasks/styles.js”, add the row; includePaths: [ './node_modules/bootstrap-sass/assets/stylesheets' ] to the object passed to sass() (Currently row 18 is good)
3) In fonts-job defined in “gulp/config.js”, add the files to be copied; 'node_modules/bootstrap-sass/assets/fonts/**/*', 
4) Restart gulp

**Comment by jakemmarsh** [comment]
Version bumped in 810934a14138898f82fd986a6500450c0f1f1322. Thanks for that guide!
