### ISSUE TITLE
Add includePaths to gulp style via configuration

### ISSUE THREAD

**Issue by victmo** [jakemmarsh/angularjs-gulp-browserify-boilerplate#71]
Fisrt of all, thanks for this great, clean and simple boilerplate.

I noticed that many people are having issues with bootstrap and bower. I did.

What I ended up doing was adding `includePaths` to the *styles* task via the configuration, something like:

```js
.pipe(sass({
    ...
    includePaths: config.styles.sassIncludePaths
}))
```

And then in the *config.js* file we can do something like this:

```js
'styles': {
    ...
    'sassIncludePaths': [
        ...
        'node_modules/bootstrap-sass/assets/stylesheets',
        'node_modules/another-npm-package/assets'
    ]
}
```

This way we can easily `@import` components to our main.scss file...

```sass
@import 'bootstrap'
```

...and we avoid hacking the gulp tasks.

**Comment by jakemmarsh** [comment]
Added in #72
