### ISSUE TITLE
Bulk Require for Sub Modules

### ISSUE THREAD

**Issue by hoodsy** [jakemmarsh/angularjs-gulp-browserify-boilerplate#73]
I was wondering if there was anyway to utilize the bulk-require approach for sub modules.

So, for example, I might have a top level _index.js that is bulk requiring all of my controllers. Would it be possible to replicate the functionality of this _index.js for a folder of sub modules?

Ideally, this file:
```
controllers/components/_buttons.js
```
would get required by:
```
controllers/_index.js
```

The whole purpose of this would be to avoid having to manually require the top level _index.js file in sub modules, such as
```
controllers/components/buttons/buttonCtrl.js
```

Is it clear what I'm asking, and is this at all possible? I love the bulk-require style used in _index.js, and would like to extend it for an application with deeper nesting of angular modules.

@jakemmarsh

**Comment by jakemmarsh** [comment]
Have you tried doing this in current setup? [`controllers/_index.js`](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/controllers/_index.js#L8) should already be set up to recursively require all JS files within `/controllers/*`

**Comment by hoodsy** [comment]
It works, but it requires that each sub module require the top controller module, which can get kind of messy with deeply nested modules.

**Comment by jakemmarsh** [comment]
Ahh right, missed that part of your original question!

I understand why that would get messy, but I think a solution to that problem will be a bit more involved.

The first approach that comes to mind would be that instead of mounting each controller on the `controllersModule` in each of their respective files, you could export the controller name/function and do the mounting inside `_index.js` after bulk requiring. It would look something like this:

**Controller:**
```javascript
module.exports = {
   name: 'ExampleCtrl',
   fn: function() {
      // actual controller logic
   }
};
```

**`_index.js`:**
```javascript
var controllersModule = angular.module('app.controllers', []);
var controllers = bulk(__dirname, ['./**/!(*_index|*.spec).js']);
controllers.forEach(function(controller) {
   controllersModule.controller(controller.name, controller.fn);
});
```

I think this approach should work and be relatively clean, but I'd have to try it out. What are your thoughts?

**Comment by hoodsy** [comment]
That looks great! Thank you for sharing! There is one aspect that might add a little bit of overhead, namely the organization of my modules. My project uses a component based structure, where, for example, a directive would live with its controller and service, or anything else. 

I tried this earlier today:
```javascript
'use strict';
var ComponentsModule = require('../_index');

ComponentsModule
	.directive('dropdownPrimary', require('./primary/primary.dir'))
	.directive('dropdownSecondary', require('./secondary/secondary.dir'));
```

But ideally in this example I would have a dropdowns module like ```app.components.dropdowns```, but that would take a bit more manual work.

I think I might take your solution and add a "type" property, and use that to wire up a controller, directive, etc. This could be pretty nice - thanks!

**Comment by jakemmarsh** [comment]
Ah yeah, a more complex structure might make this a bit more complicated. Let me know how your exploration goes (like I said, I'm especially curious about the effects on `@ngInject`). If we can figure out a solid approach to this, I might update the boilerplate

**Comment by jakemmarsh** [comment]
@hoodsy I got this working. It looks like a `type` property is actually required (at least with the way I'm approaching it). `bulk-require` returns an object, where the keys are the filename and the values are the export. I'm using the `type` property to determine if it should be mounted.

**controllers/example.js:**
```javascript
'use strict';

function ExampleCtrl() {

  // ViewModel
  var vm = this;

  vm.title = 'AngularJS, Gulp, and Browserify!';
  vm.number = 1234;

}

export default {
  type: 'controller',
  name: 'ExampleCtrl',
  fn: ExampleCtrl
};
```

**controllers/index.js:**
```javascript
'use strict';

var angular = require('angular');
var bulk = require('bulk-require');

var controllersModule = angular.module('app.controllers', []);

var controllers = bulk(__dirname, ['./**/!(*_index|*.spec).js']);

Object.keys(controllers).forEach(function(key) {
  var module = controllers[key];
  if ( module.type && module.type === 'controller' ) {
    controllersModule.controller(module.name, module.fn);
  }
});

module.exports = controllersModule;
```

what do you think of this?

**Comment by hoodsy** [comment]
This looks great! I am 100% going to put this into use in my project.

As I mentioned, I am using a component based structure, and have 4 top level ```_index.js``` module files, so will probably create a service that is able to easily wire these modules up.

This is going to make things a whole lot easier!

**Comment by jakemmarsh** [comment]
Let me know how converting your project goes. 

The only problem with the current approach is that the `bulk(__dirname, ['./**/!(*_index|*.spec).js']);` call is relative to the root directory when invoked, meaning it's essentially requiring all files in the `js/` directory (hence the need for the `type` property). This could be fixed by making the glob more specific, i.e. `./build/js/controllers/**/*.js` but that seems messy to me. I'll continue thinking of possible fixes.

**Comment by hoodsy** [comment]
So for the past day or so I have been working on implementing our (your) solution, and got to something that works. 
I ended up finding and loading my modules during config time with a provider. It was required that I use specific providers for controllers, filters, directives, services, etc. 

There are some hard coded values and some cleaning up to do, but I just run it at config time and the modules I have set up with ```module.exports = {type, name, fn};``` just work. I can't wait to expand this across the project!

```javascript
'use strict';

var bulk            = require('bulk-require');
var angular         = require('angular');
var GeneratorModule = require('../_index');

/**
 * @ngInject
**/
function ModuleService($controllerProvider, $compileProvider, $filterProvider, $provide) {

  var service    = {};
  service.$get   = inject;
  service.inject = inject;
  return service;

  /**
   * Taking a top level module and a path to valid submodules,
   * dynamically instantiate submodules as part of top level module.
  **/
  function inject () {
    var topModule           = angular.module('app.components', []);
    var subModules          = bulk('app/components/dropdowns', ['**/!(*.mod).js']);
    topModule.newFilter     = $filterProvider.register;
    topModule.newService    = $provide.service;
    topModule.newFactory    = $provide.factory;
    topModule.newDirective  = $compileProvider.directive;
    topModule.newController = $controllerProvider.register;

    findAttachModules(subModules, topModule)
  }

  /**
   * Recursively dig into submodule folder to find
   * and attach validly exported modules
  **/
  function findAttachModules (subModule, topModule) {
    if (isValidModule(subModule))
      attachSubmodule(subModule, topModule);
    else {
      Object.keys(subModule).forEach(function (key) {
        findAttachModules(subModule[key], topModule);
      });
    }
  }

  // Attach valid submodule to top level module
  function attachSubmodule (subModule, topModule) {
    if (subModule.type === 'controller')
      topModule.newController(subModule.name, subModule.fn);
    else if (subModule.type === 'directive')
      topModule.newDirective(subModule.name, subModule.fn);
    else if (subModule.type === 'filter')
      topModule.newFilter(subModule.name, subModule.fn);
    else if (subModule.type === 'factory')
      topModule.newFactory(subModule.name, subModule.fn);
    else if (subModule.type === 'service')
      topModule.newService(subModule.name, subModule.fn);
  }

  // Test properties of submodule
  function isValidModule (subModule) {
    if (subModule.type && subModule.name && subModule.fn)
      return true;
    else
      return false;    
  }

}

GeneratorModule.provider('ModuleService', ModuleService);
```

Let me know what you think! I had a lot of fun with this - although the recursive bit was frustrating. I settled with passing the topModule throughout to make my life easier :D

**Comment by Itagiba** [comment]
Hello, I have just begun implementing this great little seed project. However I am really having issues with adding new controllers. Outside of the views,  js/controllers and on_config.js file is there somewhere else where I need to register the controllers? I have added a couple of them in addition to your example controller in the controllers directory as follows:

```javascript
'use strict';

var controllersModule = require('./_index');

controllersModule.controller("AboutCtrl", function(){
    var vm = this;
    blog.title = 'ABOUT PAGE!';
    blog.intro = "Everything you wanted to know";
    blog.content = "Sed possit legendos ne, mea at magna adhuc, cum et affert diceret eleifend. Qui esse oratio accusamus eu, nostro urbanitas eu nam, nam in erat corpora sadipscing. Quot justo interpretaris ei sed, ea sed cibo novum instructior, his sint laoreet no. Tota ornatus cotidieque te quo, in est summo clita, hey show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing."

});

controllersModule.controller("HomeCtrl", function(){
    var vm = this;
    vm.title = 'Home Sweet Home';
    vm.number = "Number One for You";
    vm.intro = "Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing."

});

controllersModule.controller("BlogCtrl", function(){
    var vm = this;
    blog.title = 'This is The Blog Homepage!';
    blog.intro = "Let me Introduce you to A world of fun";
    blog.content = "Sed possit legendos ne, mea at magna adhuc, cum et affert diceret eleifend. Qui esse oratio accusamus eu, nostro urbanitas eu nam, nam in erat corpora sadipscing. Quot justo interpretaris ei sed, ea sed cibo novum instructior, his sint laoreet no. Tota ornatus cotidieque te quo, in est summo clita, hey show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing."

});

```

For some reason only the HomeCtrl works, which is why I am wondering if I a missing another registry as it is based on the exampleCtrl that was there before. Is there anything I am missing?

My on_config.js file is as follows:

````
'use strict';

/**
 * @ngInject
 */
function OnConfig($stateProvider, $locationProvider, $urlRouterProvider) {

  $locationProvider.html5Mode(true);

  $stateProvider

  .state('About', {
    url: '/about',
    controller: 'AboutCtrl as about',
    templateUrl: 'about.html',
    title: 'About'
  })

  .state('Home', {
    url: '/',
    controller: 'HomeCtrl as home',
    templateUrl: 'home.html',
    title: 'Home'
  })




  .state('Blog', {
    url: '/blog',
    controller: 'BlogCtrl as blog',
    templateUrl: 'blog.html',
    title: 'Blog'
  })



  $urlRouterProvider.otherwise('/');

}

module.exports = OnConfig;
```

**Comment by jakemmarsh** [comment]
Glad you were able to adapt it to your use case, @hoodsy! I understand your approach, but I'm not entirely sure if I would prefer the added complexity of using a provider versus just requiring the corresponding files in each index file (`controllers/index`, etc).

I'll continue thinking on this before implementing in master. Could you provide any input on why you went with the more complex provider approach?

**Comment by hoodsy** [comment]
My project is essentially a component library. For any basic components (and subsequent angular modules) the require approach works just fine.

The reason I sought this solution is for the inclusion of more complex components that include subdirectories. For example, another developer may make a table component structured like:

```
table/
  head/
  row/
    item/
```

So when their component is added to my component library, they can either add the ```require('index')``` line, or specify ```module.exports = { type, name, fn }``` for each module.

Both work, but I felt the ```module.exports``` pattern made things a lot easier, as they didn't have to worry about file paths or the organization of the library. Of course this is a very specific use case, and maybe it doesn't necessarily fit in the boilerplate.

**Comment by jakemmarsh** [comment]
My approach is now in master: 7b5dfef4ddd2700a5e1e33aab895a0aac2387e29

**Comment by jdrew1303** [comment]
Hey,
I realise this is a bit of an old question and angular 2 is out but one thing you can do to reduce the need to export an object is make the loader a bit smarter. My two tricks are parsing the name of the file for the type (most people append the type to the end of the item name `exampleController.js`) and pulling the function name directly using `.name` on the imported function (you could use this for both parts instead of the file name). 

This allows you to export plain functions or classes directly.
