### ISSUE TITLE
Update to ES6

### ISSUE THREAD

**Issue by jakemmarsh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#74]

**Comment by alferov** [comment]
:thumbsup: Awesome!

**Comment by jakemmarsh** [comment]
This is nearly complete in the [es6 branch](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/tree/es6). The only issue is when importing `bulk-require` in the ES6 manner, which results in errors. I've reported that [here](https://github.com/substack/bulk-require/issues/6)

**Comment by jakemmarsh** [comment]
Done in #85. Still waiting on that bulk-require issue, stuck with the ES5 `require` call for now
