### ISSUE TITLE
JS Scripts

### ISSUE THREAD

**Issue by boadude** [jakemmarsh/angularjs-gulp-browserify-boilerplate#79]
JS Librarys for example ... D3 library where i must put ? in which folder?

**Comment by mujx** [comment]
Install it with npm, `npm i --save d3`
and require it in your `app/js/main.js` file.
```js
var angular = require('angular');

require('d3');
...
```
If you use an angular module like `angular-nvd3` add it to the requires also

```js
 var requires = [
     ...
     'nvd3',
     ...
    ];

```

**Comment by boadude** [comment]
Ok thanks, and for install external libraries? Like in .js format only and
use inside of controllers?

**Comment by teamjordy** [comment]
Tried creating a vendor folder within the 'js' folder and gulp doesn't seem to be picking it up. It looks like gulp will build anything in the js folder, so not sure what the problem could be.

**Comment by jakemmarsh** [comment]
@teamjordy currently, the gulp `browserify` task is only [set up to process](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/config.js#L51) `app/js/main.js` and any resulting dependencies. That means the files in your newly created `vendor/` directory would have to be included in some other file that is eventually included by `main.js`. 

You should be able to fix this by changing the line linked above to `'entries'   : ['./app/js/**/*.js']`

**Comment by boadude** [comment]
Ok, Great.
