### ISSUE TITLE
how to add new modules

### ISSUE THREAD

**Issue by duardito** [jakemmarsh/angularjs-gulp-browserify-boilerplate#80]
Hi,
I want to add new modules, how is it the correct way to do it  in your boilerplate.
Please, can you show me an example where I can see all files that I have to modify to add a new module.
thanks

**Comment by jakemmarsh** [comment]
Have you read the readme and looked through the example code? What kind of module are you attempting to add?

Essentially, you create your new module in the correct directory, require the parent `_index.js` file, and mount it on that. The bulk require within each `_index.js` file will take care of the rest. Please see [`controllers/example.js`](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/controllers/example.js) and [`controllers/_index.js`](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/controllers/_index.js) for an example of how this works.
