### ISSUE TITLE
Relative path in gulp/tasks/views.js

### ISSUE THREAD

**Issue by loulouDelPays** [jakemmarsh/angularjs-gulp-browserify-boilerplate#82]
There is a relative path in gulp/tasks/views.js (line 12). If someone wants to use a different path for his index.html file, he or she would need to edit views.js. I guess the index path should be written in gulp/config.js.

**Comment by jakemmarsh** [comment]
good catch! fixed in fb7b39f776ac7dc1db98e05231ed6021bcb16ed4
