### ISSUE TITLE
Error on gulp dev

### ISSUE THREAD

**Issue by boadude** [jakemmarsh/angularjs-gulp-browserify-boilerplate#86]
<code>
import fss22         from 'fs';
^^^^^^

SyntaxError: Unexpected reserved word
</code>

**Comment by boadude** [comment]
Sorry...
<code>
import fs from 'fs';
</code>

that was the original line.

**Comment by jakemmarsh** [comment]
Have you pulled `master` recently? I did a handful of updates yesterday, including updating the entire project to ES6. I was not able to replicate this error with a fresh clone/`npm install`

**Comment by boadude** [comment]
Yes, i notice. i clone the repository a few hours ago... (2 hours). Fresh install

**Comment by jakemmarsh** [comment]
Hm. Can you provide the full stack trace for the error?

**Comment by boadude** [comment]
Sure... wait...

**Comment by jakemmarsh** [comment]
Also, is your gulpfile now titled `gulpfile.babel.js` and the `babel-core` dependency installed? All Gulp files/tasks should be transpiled before running, which should avoid this error

**Comment by boadude** [comment]
So, the problem was that i must run the console like admin...

<code>
$ gulp dev
[15:40:43] Requiring external module babel-core/register
[15:41:30] Using gulpfile ~\Projects\testAngular\gulpfile.babel.js
</code>

Now works ok.

**Comment by jakemmarsh** [comment]
Hm, strange you have to run as admin but glad you have it figured out! :+1:

**Comment by boadude** [comment]
I am glad for this update to ES6, very helpful repository! Thanks for this
Jake!
