### ISSUE TITLE
Failed to decode downloaded font: http://localhost:3000/fonts/bootstrap/glyphicons-halflings-regular.woff2

### ISSUE THREAD

**Issue by justin-umesh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#89]
fonts: {
    src: ['app/fonts/**/*'],
    dest: 'build/fonts/bootstrap'
  },

**Comment by hoodsy** [comment]
your going to want to add your **font file extensions** to the browserSync server.

in ```gulp/tasks/browserSync.js```, **line 11**, add the desired font file types (woff2, otf, ttf, etc)

@justin-umesh

**Comment by justin-umesh** [comment]
@hoodsy 

Thanks a lot, Its working fine..

**Comment by justin-umesh** [comment]
@hoodsy 

Can please help me on adding jquery and bootstrap.js.

I am finding very difficult to include,

Thanks in advance.

**Comment by jakemmarsh** [comment]
@justin-umesh both of those can be installed via npm. So run `npm install --save-dev jquery bootstrap` then do `import jquery from 'jquery'` and `import bootstrap from 'bootstrap'` anywhere in your JS

**Comment by justin-umesh** [comment]
@jakemmarsh 

I have installed the jquery, added this line at main.js import jquery from 'jquery';

added the below lines.
$('body').on('click', function(){
  	alert('hey');
  });

finally i am getting this error on browser console.
ReferenceError: $ is not defined

Thanks in advance.
