### ISSUE TITLE
including external library like jquery

### ISSUE THREAD

**Issue by justin-umesh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#90]
I have installed the jquery, added below line at main.js 
```javascript
import jquery from 'jquery';
```

added the below lines.
```javascript
$('body').on('click', function(){
alert('hey');
});
```
finally i am getting below error on browser console.
```
ReferenceError: $ is not defined
```

Thanks in advance.

**Comment by jakemmarsh** [comment]
This is because you're using the `$` variable, but defining jquery as `jquery`. So you either need to change your import statement to `import $ from 'jquery'` or your invocation to `jquery('body')...`

**Comment by justin-umesh** [comment]
@jakemmarsh 
I have tried with 'jquery' that also doesn't work.

**Comment by jakemmarsh** [comment]
@justin-umesh did you try `import $ from 'jquery'` then?

**Comment by justin-umesh** [comment]
its working fine. thanks a lot.
