### ISSUE TITLE
Error in plugin 'gulp-karma' when i started with gulp test

### ISSUE THREAD

**Issue by justin-umesh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#92]

**Comment by jakemmarsh** [comment]
It would be helpful if you could provide more information than that. What is the exact error you're seeing?

**Comment by justin-umesh** [comment]
I have upgraded all packages to latest version. after that i ran the gulp test command. then i ma getting the error.

"devDependencies": {
    "angular": "^1.4.7",
    "angular-mocks": "^1.4.7",
    "angular-ui-bootstrap": "^0.14.2",
    "angular-ui-router": "^0.2.15",
    "babel-core": "^5.8.25",
    "babelify": "^6.4.0",
    "brfs": "^1.4.1",
    "browser-sync": "^2.9.11",
    "browserify": "^11.2.0",
    "browserify-istanbul": "^0.2.1",
    "browserify-ngannotate": "^1.0.1",
    "bulk-require": "^0.2.1",
    "bulkify": "^1.1.1",
    "debowerify": "^1.3.1",
    "del": "^0.1.3",
    "gulp": "^3.9.0",
    "gulp-angular-templatecache": "^1.8.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-changed": "^1.3.0",
    "gulp-gzip": "^1.2.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.3.0",
    "gulp-jshint": "^1.11.2",
    "gulp-karma": "0.0.5",
    "gulp-notify": "^2.2.0",
    "gulp-protractor": "^1.0.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.0.4",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-streamify": "1.0.2",
    "gulp-uglify": "^1.4.2",
    "gulp-util": "^3.0.7",
    "imagemin-pngcrush": "^4.1.0",
    "isparta": "^3.1.0",
    "jquery": "^2.1.4",
    "jshint-stylish": "^2.0.1",
    "karma": "^0.13.13",
    "karma-babel-preprocessor": "^5.2.2",
    "karma-browserify": "^4.4.0",
    "karma-chrome-launcher": "^0.2.1",
    "karma-coverage": "git://github.com/douglasduteil/karma-coverage#next",
    "karma-firefox-launcher": "^0.1.6",
    "karma-jasmine": "^0.3.6",
    "pretty-hrtime": "^1.0.1",
    "protractor": "^2.5.1",
    "run-sequence": "^1.1.4",
    "tiny-lr": "0.2.1",
    "uglifyify": "^3.0.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.4.0"
  },
  "scripts": {
    "pretest": "npm install",
    "test": "karma start test/karma.conf.js",
    "preprotractor": "npm run update-webdriver",
    "protractor": "npm run protractor test/protractor.conf.js"
  }

**Comment by jakemmarsh** [comment]
You still didn't provide the exact error that you're receiving. Regardless, it is not surprising that updating every single package broke the tests (and probably the app). This isn't a problem with the boilerplate itself. If you want to update each individual package, you'll have to check their respective changelogs and make any necessary changes to avoid breaking.
