### ISSUE TITLE
<ng-include src="includes/header.html"></ng-include>

### ISSUE THREAD

**Issue by justin-umesh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#93]
Header
ngInclude: undefined

**Comment by jakemmarsh** [comment]
This is not an issue, you aren't specifying what changes you have made or what the specific error is that you're seeing. Either way, I'm guessing this particular error is related you updating every single npm package in the repo, which you mentioned doing in #92.

**Comment by justin-umesh** [comment]
<ng-include src="includes/header.html"></ng-include>

      
      <div ui-view></div>

      
      <ng-include src="includes/footer.html"></ng-include>

      
      <script src="js/main.js"></script>

**Comment by justin-umesh** [comment]
directory structure
<img width="219" alt="screen shot 2015-10-27 at 11 06 20 am" src="https://cloud.githubusercontent.com/assets/11955406/10750402/e7947be6-7c9a-11e5-834c-dcd69e1372ab.png">

**Comment by bbjoern** [comment]
Had the same error - try as follows with two -->  '

 <ng-include src="'includes/footer.html'"></ng-include>
