### ISSUE TITLE
Sourcemap adding to css and js after build which causing to make file size bigger (in MBs)

### ISSUE THREAD

**Issue by justin-umesh** [jakemmarsh/angularjs-gulp-browserify-boilerplate#94]
after the gulp dev when i am checking my main.js file size has been increased to 4.6MB

**Comment by jakemmarsh** [comment]
Right, but this only occurs in production and if you have the `config.browserify.createSourcemap` flag set to true. This can be seen [here](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserify.js#L54)

If you don't want this functionality, remove [line 54](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserify.js#L54) and [line 63](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserify.js#L63) of the Browserify Gulp task.
