### ISSUE TITLE
Project versioning problem

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#97]
I have problem with running tests. 
Now, I wanted to compare a clean boilerplate project with what I have, but they are not the same any more.

How come the version is still the same "version": "0.1.0", but the project is not?

My version, from like 7 months ago, is 0.1.0, and the version today is the same?

There is no longer a gulpfile, but instead there is now a gulpfile.babel.js. 
The readme file is no longer up to date. 

Is the project being maintained, and in which direction? How can I use the current version, and is there a way to access the same version I've cloned 7 months ago?

**Comment by jakemmarsh** [comment]
This project is still being updated and maintained. You are right though, versioning has not been done correctly. I've now bumped the version to 1.0 and marked it as an [official release](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/releases/tag/v1.0.0) and will attempt to continue this practice moving forward.

**Comment by mnemanja** [comment]
Okay, makes sense. Thanks!

I found this out because I needed to test something on the clean boilerplate, but could not find version 0.1.0. It would be nice to have access to previous releases.

Cheers
