### ISSUE TITLE
Karma code coverage dumps *.js.html files right next to the .js files, and not where it's configured

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#98]
So, this is my setup, which is basically the default with the "coverageReporter" property added and set to point to the "coverage" folder. The "coverage" folder gets populated in any case, but the "app" folder gets the .js.html dump as well.

    config.set({

        basePath: '../',
        frameworks: ['jasmine', 'browserify'],
        preprocessors: {
            'app/js/**/*.js': ['browserify', 'coverage']
        },
        browsers: ['Chrome'],
        reporters: ['progress', 'coverage'],

        autoWatch: true,

        browserify: {
            debug: true,
            extensions: ['.js', '.jsx'],
            transform: [
                'babelify',
                'bulkify',
                istanbul({
                    instrumenter: isparta,
                    ignore: ['**/node_modules/**', '**/test/**']
                })
            ]
        },

        coverageReporter: {
            type : 'html',
            dir : 'coverage/'
        },

        proxies: {
            '/': 'http://localhost:9876/'
        },

        urlRoot: '/__karma__/',
        colors: true,
        captureTimeout: 60000,
        singleRun: false,

        files: [
            // app-specific code
            'app/js/main.js',

            // 3rd-party resources
            'node_modules/angular-mocks/angular-mocks.js',

            // test files
            'test/unit/**/*.js'
        ]

    });

By default this behavior is there, the app folder gets polluted. Would be nice to have it by default.

The "coverageReporter" property does not react to the changes that I try applying. Can this be fixed?

**Comment by mnemanja** [comment]
The "coverage" folder appears even when I remove the preprocessor:

    preprocessors: {
        'app/js/**/*.js': ['browserify', 'coverage']
    },

**Comment by jakemmarsh** [comment]
I'm not sure why you've added the `coverageReporter` property at all. Code coverage is still generated correctly on a fresh install without this addition. I would recommend removing it.
